(function(){
  const page=document.body.dataset.page,app=document.querySelector('#app');if(!['users','departments','settings'].includes(page))return;
  const incoming=AppData.incoming(),icon=p=>`<svg viewBox="0 0 24 24" aria-hidden="true">${p}</svg>`,I={more:'<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>',building:'<path d="M4 21V6l8-3 8 3v15M8 9h2m4 0h2m-8 4h2m4 0h2"/>',user:'<circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0116 0"/>'};
  const head=(title,desc,action='')=>`<section class="list-page-head"><div><span class="pro-eyebrow">الإدارة والحوكمة</span><h2>${title}</h2><p>${desc}</p></div>${action}</section>`;
  if(page==='users'){
    const users=DemoData.users.map((u,i)=>({...u,lastLogin:i?'أمس 14:20':'اليوم 09:31'}));
    app.innerHTML=head('المستخدمون والصلاحيات','إدارة حسابات الموظفين والأدوار التشغيلية.',`<button class="btn btn-primary" id="addUser">+ إضافة مستخدم</button>`)+`<section class="list-toolbar"><label class="list-search">${icon(I.user)}<input id="userSearch" placeholder="ابحث بالاسم أو البريد أو القسم..."></label><div class="list-filter"><label>الدور<select id="userRole"><option value="">كل الأدوار</option><option>مدير النظام</option><option>رئيس البلدية</option><option>مدير عام</option><option>موظف الديوان</option><option>مدير دائرة</option><option>موظف</option></select></label><label>الحالة<select id="userStatus"><option value="">كل الحالات</option><option>نشط</option><option>موقوف</option></select></label></div></section><section class="list-panel"><div class="list-panel-head"><div><h3>دليل المستخدمين</h3><span id="userCount">${users.length} مستخدمين</span></div></div><div class="list-table-wrap"><table class="list-table"><thead><tr><th>المستخدم</th><th>المسمى الوظيفي</th><th>القسم</th><th>الدور</th><th>الحالة</th><th>آخر دخول</th><th></th></tr></thead><tbody id="usersBody"></tbody></table></div></section>`;
    const render=data=>{document.querySelector('#usersBody').innerHTML=data.map((u,i)=>`<tr><td><span class="person-cell"><span class="avatar avatar-sm">${u.name[0]}</span><span><b>${u.name}</b><small>${u.email}</small></span></span></td><td>${u.title}</td><td>${u.dept}</td><td>${badge(u.role)}</td><td>${badge(u.status)}</td><td>${u.lastLogin}</td><td><div class="actions-menu"><button class="table-action" data-user-menu="${i}" aria-label="إجراءات ${u.name}">${icon(I.more)}</button><div class="action-dropdown"><button>عرض</button><button>تعديل</button><button>تغيير الدور</button><button>${u.status==='نشط'?'إيقاف':'تفعيل'}</button></div></div></td></tr>`).join('');document.querySelector('#userCount').textContent=`${data.length} مستخدمين`};render(users);
    const filter=()=>{const q=document.querySelector('#userSearch').value.toLowerCase(),role=document.querySelector('#userRole').value,status=document.querySelector('#userStatus').value;render(users.filter(u=>(!q||Object.values(u).join(' ').toLowerCase().includes(q))&&(!role||u.role===role)&&(!status||u.status===status)))};document.addEventListener('input',e=>{if(e.target.matches('#userSearch,#userRole,#userStatus'))filter()});document.addEventListener('change',e=>{if(e.target.matches('#userRole,#userStatus'))filter()});document.addEventListener('click',e=>{const button=e.target.closest('[data-user-menu]');document.querySelectorAll('.action-dropdown.open').forEach(x=>{if(x!==button?.nextElementSibling)x.classList.remove('open')});if(button)button.nextElementSibling.classList.toggle('open');if(e.target.closest('.action-dropdown button'))toast('هذا الإجراء سيُرسل إلى نظام المستخدمين بعد ربط الـBackend','info')});document.querySelector('#addUser').onclick=()=>toast('إضافة المستخدم تحتاج خدمة المستخدمين والصلاحيات في بوابة البلدية','info');return;
  }
  if(page==='departments'){
    app.innerHTML=head('الأقسام والدوائر','متابعة الهيكل الإداري وحجم العمل ومستوى الإنجاز.')+`<div class="department-grid">${DemoData.departments.map((name,i)=>{const items=incoming.filter(r=>r.department===name),late=items.filter(r=>r.status==='متأخر').length,done=items.filter(r=>['تم الإنجاز','مؤرشف'].includes(r.status)).length,rate=items.length?Math.round(done/items.length*100):0;return `<article class="department-card"><div class="department-head"><span>${icon(I.building)}</span><div><h3>${name}</h3><small>مدير القسم: ${['محمد أحمد','سارة خالد','أحمد محمد'][i%3]}</small></div>${badge('نشط')}</div><div class="department-stats"><span><b>${3+i}</b><small>الموظفون</small></span><span><b>${items.length}</b><small>المراسلات الحالية</small></span><span><b class="danger">${late}</b><small>المتأخرة</small></span></div><div class="dept-progress"><div><span>نسبة الإنجاز</span><b>${rate}%</b></div><i><em style="width:${rate}%"></em></i></div><button class="btn btn-light department-open" data-name="${name}" data-count="${items.length}" data-late="${late}" data-rate="${rate}">عرض معلومات القسم</button></article>`}).join('')}</div>`;document.addEventListener('click',e=>{const b=e.target.closest('.department-open');if(!b)return;const modal=document.createElement('div');modal.className='modal open';modal.innerHTML=`<div class="modal-box"><h3>${b.dataset.name}</h3><div class="department-stats"><span><b>${b.dataset.count}</b><small>مراسلات حالية</small></span><span><b>${b.dataset.late}</b><small>متأخرة</small></span><span><b>${b.dataset.rate}%</b><small>إنجاز</small></span></div><button class="btn btn-primary" data-close>إغلاق</button></div>`;document.body.append(modal);modal.querySelector('[data-close]').onclick=()=>modal.remove()});return;
  }
  app.innerHTML=head('إعدادات النظام','إعدادات وحدة المراسلات التي سيعتمدها Backend البلدية.')+`<form class="card settings-form" id="settingsForm"><div class="form-grid"><div class="field span-2"><label>اسم البلدية</label><input value="بلدية المغازي" readonly></div><div class="field"><label>السنة المالية</label><select><option>2026</option></select></div><div class="field"><label>نظام الترقيم</label><select><option>سنوي مستقل للوارد والصادر</option></select></div><div class="field span-2"><label>البريد الرسمي</label><input type="email" placeholder="البريد الرسمي"></div><div class="field span-2"><label>العنوان</label><input value="مخيم المغازي – فلسطين"></div></div><div class="form-actions-inline"><button class="btn btn-primary">حفظ الإعدادات</button></div></form>`;document.querySelector('#settingsForm').onsubmit=e=>{e.preventDefault();toast('تم حفظ إعدادات العرض؛ الحفظ المركزي بعد ربط الـBackend','info')};
})();
