(function(){
  if(document.body.dataset.page!=='approvals')return;
  const app=document.querySelector('#app');let filter='all';
  const all=()=>[...CorrespondenceSystem.list('outgoing').map(x=>({...x,_type:'outgoing'})),...CorrespondenceSystem.list('internal').map(x=>({...x,_type:'internal'}))].filter(x=>['بانتظار التدقيق','بانتظار الاعتماد','معاد للتعديل','معتمدة'].includes(x.status)||x.extensionRequest?.status==='بانتظار الموافقة');
  const categories=[['all','جميع الطلبات',()=>true],['review','بانتظار التدقيق',x=>x.status==='بانتظار التدقيق'],['approve','بانتظار الاعتماد',x=>x.status==='بانتظار الاعتماد'],['extension','طلبات التمديد',x=>x.extensionRequest?.status==='بانتظار الموافقة'],['returned','معادة للتعديل',x=>x.status==='معاد للتعديل'],['done','معتمدة',x=>x.status==='معتمدة']];
  app.innerHTML=`<section class="list-page-head"><div><span class="pro-eyebrow">المراجعة والقرار الإداري</span><h2>صندوق الاعتمادات</h2><p>تدقيق الكتب، اعتمادها، إعادتها للتعديل، والبت في طلبات تمديد المهلة.</p></div></section><div class="approval-board"><nav class="approval-nav" id="approvalNav"></nav><section class="approval-list"><header class="approval-list-head"><div><h3 id="approvalTitle">جميع الطلبات</h3><small id="approvalCount"></small></div><button class="btn btn-light btn-sm" id="refreshApprovals">تحديث</button></header><div id="approvalItems"></div></section></div>`;
  const stage=status=>`<div class="approval-stage" title="مسار الاعتماد"><i class="${['بانتظار الاعتماد','معتمدة'].includes(status)?'done':'current'}"></i><i class="${status==='معتمدة'?'done':status==='بانتظار الاعتماد'?'current':''}"></i><i class="${status==='معتمدة'?'done':''}"></i></div>`;
  const askReason=()=>new Promise(resolve=>{const modal=document.createElement('div');modal.className='modal open';modal.innerHTML='<form class="modal-box"><h3>إعادة المراسلة للتعديل</h3><p class="muted">اكتب الملاحظات المطلوب تنفيذها قبل إعادة الإرسال.</p><div class="field"><label>سبب الإعادة <i>*</i></label><textarea name="reason" rows="4" required></textarea></div><div class="actions"><button class="btn btn-primary">تأكيد الإعادة</button><button class="btn btn-light" type="button" data-cancel>إلغاء</button></div></form>';document.body.append(modal);modal.querySelector('form').onsubmit=e=>{e.preventDefault();const reason=e.target.reason.value.trim();if(reason){modal.remove();resolve(reason)}};modal.querySelector('[data-cancel]').onclick=()=>{modal.remove();resolve('')}});
  function render(){const data=all(),category=categories.find(x=>x[0]===filter),rows=data.filter(category[2]);document.querySelector('#approvalNav').innerHTML=categories.map(([key,label,test])=>`<button data-filter="${key}" class="${key===filter?'active':''}">${label}<i>${data.filter(test).length}</i></button>`).join('');document.querySelector('#approvalTitle').textContent=category[1];document.querySelector('#approvalCount').textContent=`${rows.length} طلبات`;document.querySelector('#approvalItems').innerHTML=rows.length?rows.map(x=>`<article class="approval-card"><div><h4>${x.subject}</h4><p>${x.number||'مسودة دون رقم نهائي'} · ${x.department||x.from||'—'} · ${x.to||'—'}</p><div class="approval-meta"><span>${x._type==='outgoing'?'كتاب صادر':'مراسلة داخلية'}</span><span>${x.status}</span>${x.priority?`<span>${x.priority}</span>`:''}${x.extensionRequest?.status==='بانتظار الموافقة'?`<span>تمديد إلى ${x.extensionRequest.newDueDate}</span>`:''}</div>${stage(x.status)}</div><div class="approval-actions">${x.extensionRequest?.status==='بانتظار الموافقة'?`<button class="btn btn-primary" data-extension="approve" data-type="${x._type}" data-id="${x.id||x.number}">قبول التمديد</button><button class="btn btn-light" data-extension="reject" data-type="${x._type}" data-id="${x.id||x.number}">رفض</button>`:x.status==='بانتظار التدقيق'||x.status==='بانتظار الاعتماد'?`<button class="btn btn-primary" data-approve data-type="${x._type}" data-id="${x.id||x.number}">${x.status==='بانتظار التدقيق'?'اجتاز التدقيق':'اعتماد نهائي'}</button><button class="btn btn-light" data-return data-type="${x._type}" data-id="${x.id||x.number}">إعادة للتعديل</button>`:''}<a class="btn btn-light" href="correspondence-details.html?type=${x._type}&number=${encodeURIComponent(x.number)}">عرض</a></div></article>`).join(''):'<div class="approval-empty"><b>لا توجد طلبات في هذا التصنيف</b><p>ستظهر المسودات هنا عند إرسالها للتدقيق أو الاعتماد.</p></div>'}
  document.querySelector('#approvalNav').onclick=e=>{const b=e.target.closest('[data-filter]');if(!b)return;filter=b.dataset.filter;render()};document.querySelector('#refreshApprovals').onclick=()=>{render();toast('تم تحديث صندوق الاعتمادات')};
  document.querySelector('#approvalItems').onclick=async e=>{const button=e.target.closest('button[data-id]');if(!button)return;const type=button.dataset.type,id=button.dataset.id,current=CorrespondenceSystem.find(type,id);if(button.hasAttribute('data-approve')&&!CorrespondenceSystem.can(current?.status==='بانتظار التدقيق'?'review':'approve')){toast('ليس لديك صلاحية تنفيذ هذا القرار','error');return}if(button.dataset.extension&&!CorrespondenceSystem.can('approve_extension')){toast('ليس لديك صلاحية اعتماد طلبات التمديد','error');return}try{if(button.hasAttribute('data-approve')){if(await confirmAction({title:'تأكيد القرار',message:'سيتم تسجيل اسم منفذ القرار ووقته في سجل العمليات.',confirmText:'تأكيد'}))CorrespondenceSystem.approve(type,id)}else if(button.hasAttribute('data-return')){const reason=await askReason();if(reason)CorrespondenceSystem.returnForEdit(type,id,reason)}else if(button.dataset.extension){CorrespondenceSystem.decideExtension(type,id,button.dataset.extension==='approve','تمت مراجعة الطلب')}render();toast('تم تسجيل القرار')}catch(error){toast(error.message,'error')}};
  render();
})();
