(function(){
  const type=document.body.dataset.page;if(!['incoming','outgoing'].includes(type))return;const selected=new Set(),panel=document.querySelector('.list-panel');if(!panel)return;
  panel.insertAdjacentHTML('afterend',`<div class="bulk-action-bar" id="bulkActionBar"><b><span id="selectedCount">0</span> محددة</b><button class="btn btn-light" id="exportSelected">تصدير المحدد</button>${type==='incoming'?'<button class="btn btn-primary" id="processSelected">بدء المعالجة</button>':''}<button class="btn btn-quiet" id="clearSelected">إلغاء التحديد</button></div>`);
  const tbody=document.querySelector('#listBody'),bar=document.querySelector('#bulkActionBar');
  function sync(){bar.classList.toggle('open',selected.size>0);document.querySelector('#selectedCount').textContent=selected.size;document.querySelectorAll('.row-select').forEach(box=>box.checked=selected.has(box.value));const all=[...document.querySelectorAll('.row-select')];const master=document.querySelector('.select-visible');if(master){master.checked=all.length>0&&all.every(x=>x.checked);master.indeterminate=all.some(x=>x.checked)&&!master.checked}}
  function inject(){const head=document.querySelector('.list-table thead tr');if(head&&!head.querySelector('.select-visible'))head.insertAdjacentHTML('afterbegin','<th><input class="select-visible" type="checkbox" aria-label="تحديد النتائج الظاهرة"></th>');tbody.querySelectorAll('tr').forEach(row=>{if(row.querySelector('.empty-state')||row.querySelector('.row-select'))return;const number=row.querySelector('.row-id b')?.textContent;if(number)row.insertAdjacentHTML('afterbegin',`<td><input class="row-select" type="checkbox" value="${number}" aria-label="تحديد ${number}"></td>`)});sync()}
  new MutationObserver(inject).observe(tbody,{childList:true});inject();
  panel.addEventListener('change',e=>{if(e.target.matches('.row-select')){e.target.checked?selected.add(e.target.value):selected.delete(e.target.value);sync()}if(e.target.matches('.select-visible')){document.querySelectorAll('.row-select').forEach(box=>{box.checked=e.target.checked;e.target.checked?selected.add(box.value):selected.delete(box.value)});sync()}});
  document.querySelector('#clearSelected').onclick=()=>{selected.clear();sync()};
  document.querySelector('#exportSelected').onclick=()=>{const rows=CorrespondenceSystem.list(type).filter(x=>selected.has(x.number));const data=[['الرقم','التاريخ','الموضوع','الجهة','القسم','الحالة'],...rows.map(x=>[x.number,x.date,x.subject,x.sender||x.to||'',x.department||'',x.status])],csv='\ufeff'+data.map(row=>row.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\r\n'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`${type}-selected.csv`;a.click();URL.revokeObjectURL(url);CorrespondenceSystem.audit('تصدير مراسلات محددة',{type,count:rows.length});toast('تم تصدير المراسلات المحددة')};
  document.querySelector('#processSelected')?.addEventListener('click',async()=>{if(!CorrespondenceSystem.can('transfer')){toast('ليس لديك صلاحية بدء المعالجة الجماعية','error');return}if(!(await confirmAction({title:'بدء معالجة المراسلات',message:`سيتم تحديث ${selected.size} مراسلات إلى قيد المعالجة.`,confirmText:'تأكيد'})))return;selected.forEach(number=>CorrespondenceSystem.update('incoming',number,{status:'قيد المعالجة'},'بدء معالجة جماعية'));selected.clear();toast('تم تحديث المراسلات المحددة');setTimeout(()=>location.reload(),500)});
})();
