(function(){
  const q=new URLSearchParams(location.search),type=q.get('type')==='internal'?'internal':'outgoing',number=q.get('number'),data=type==='internal'?AppData.internal():AppData.outgoing(),item=data.find(r=>r.number===number)||data[0],key=type==='internal'?'municipalityInternal':'municipalityOutgoing',back=type==='internal'?'internal.html':'outgoing.html';
  if(!item){document.querySelector('#app').innerHTML='<div class="empty-state">تعذر العثور على المراسلة المطلوبة</div>';return}
  const icon=p=>`<svg viewBox="0 0 24 24" aria-hidden="true">${p}</svg>`,I={file:'<path d="M14 2H6v20h12V6z"/><path d="M14 2v4h4M9 13h6M9 17h4"/>',print:'<path d="M7 8V3h10v5M7 17H4v-7h16v7h-3M7 14h10v7H7z"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',user:'<circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0116 0"/>',building:'<path d="M4 21V6l8-3 8 3v15M8 9h2m4 0h2"/>'};
  const field=(label,value,glyph)=>`<div class="record-field"><span>${icon(glyph)}</span><div><small>${label}</small><b>${value||'—'}</b></div></div>`;
  document.querySelector('#app').innerHTML=`<nav class="record-breadcrumb"><a href="${back}">${type==='internal'?'المراسلات الداخلية':'البريد الصادر'}</a><span>/</span><b>${item.number}</b></nav><section class="record-hero"><div class="record-identity"><span class="record-file-icon">${icon(I.file)}</span><div><span class="record-kicker">${type==='internal'?(item.type||item.kind||'مراسلة داخلية'):'كتاب صادر'}</span><h2>${item.number} · ${item.subject}</h2><p>${item.date} · ${item.confidentiality||'عادي'}</p></div></div><div class="record-hero-side"><div class="record-state"><small>الحالة</small><span id="genericStatus">${badge(item.status)}</span></div><div class="record-actions"><button class="btn btn-primary" id="followRecord">${type==='internal'?'تحديث الحالة':'متابعة الرد'}</button><button class="btn btn-light" id="finishGeneric">إنهاء</button><button class="btn btn-light" onclick="window.print()">${icon(I.print)} طباعة</button><a class="btn btn-quiet" href="${back}">رجوع</a></div></div></section><div class="record-layout"><main><section class="record-panel"><header><span>${icon(I.file)}</span><div><h3>بيانات المراسلة</h3><p>البيانات الرسمية المسجلة</p></div></header><div class="record-fields">${field('الرقم',item.number,I.file)}${field('التاريخ',item.date,I.clock)}${field(type==='internal'?'من':'الجهة المرسل إليها',item.from||item.to,I.building)}${field(type==='internal'?'إلى':'القسم المنشئ',item.to||item.department,I.building)}${field('الموظف المسؤول',item.employee,I.user)}${field('الأولوية',item.priority||'عادي',I.clock)}<div class="record-field wide"><span>${icon(I.file)}</span><div><small>الموضوع</small><b>${item.subject}</b></div></div></div></section><section class="record-panel"><header><span>${icon(I.file)}</span><div><h3>محتوى المراسلة</h3></div></header><p class="record-body">${item.body||'لم يتم إدخال نص تفصيلي لهذه المراسلة.'}</p></section></main><aside><section class="record-panel"><header><span>${icon(I.clock)}</span><div><h3>سجل المتابعة</h3></div></header><div class="record-timeline" id="genericTimeline"><article class="done"><i></i><div><b>إنشاء المراسلة</b><p>${item.from||item.department||'بلدية المغازي'}</p><time>${item.date}</time></div></article><article class="current"><i></i><div><b>${item.status}</b><p>${type==='internal'?'بانتظار إجراء الجهة المستلمة':'متابعة التسليم والرد'}</p><time>الحالة الحالية</time></div></article></div></section></aside></div>`;
  const sla=CorrespondenceSystem.sla(item),actions=document.querySelector('.record-actions'),aside=document.querySelector('.record-layout aside');
  document.querySelector('.record-state').insertAdjacentHTML('beforeend',`<small class="sla-indicator sla-${sla.state}">${sla.label}</small>`);actions.querySelector('button[onclick]')?.removeAttribute('onclick');actions.querySelectorAll('button')[2].id='printGeneric';actions.insertAdjacentHTML('afterbegin','<button class="btn btn-light" id="requestExtension">طلب تمديد</button>');
  aside.insertAdjacentHTML('beforeend',`<section class="record-panel"><header><span>${icon(I.file)}</span><div><h3>إصدارات الوثيقة</h3><p>لا يتم استبدال النسخ السابقة</p></div></header><div class="version-list">${(item.versions||[{version:1,label:'النسخة المسجلة',createdAt:item.createdAt||item.date,createdBy:item.createdBy||'مستخدم البلدية'}]).map(v=>`<article><b>الإصدار ${v.version}</b><small>${v.label||''} · ${v.createdBy||'—'}</small><time>${v.createdAt?new Date(v.createdAt).toLocaleDateString('ar-PS'):'—'}</time></article>`).join('')}</div></section>`);
  const save=status=>{try{const updated=CorrespondenceSystem.setStatus(type,item.id||item.number,status);Object.assign(item,updated);document.querySelector('#genericStatus').innerHTML=badge(status);document.querySelector('#genericTimeline').insertAdjacentHTML('beforeend',`<article class="current"><i></i><div><b>${status}</b><p>تم تحديث الحالة</p><time>الآن</time></div></article>`);toast(`تم تحديث الحالة إلى ${status}`)}catch(error){toast(error.message,'error')}};
  document.querySelector('#followRecord').textContent=type==='outgoing'&&item.status==='معتمدة'?'تسجيل الإرسال':type==='internal'?'تحديث الحالة':'متابعة الرد';document.querySelector('#followRecord').onclick=()=>save(type==='internal'?'قيد المعالجة':item.status==='معتمدة'?'تم الإرسال':'بانتظار الرد');document.querySelector('#finishGeneric').onclick=async()=>{if(await confirmAction({title:'إنهاء المراسلة',message:'سيتم تسجيل المراسلة كمكتملة.',confirmText:'إنهاء'}))save('تم الإنجاز')};document.querySelector('#printGeneric').onclick=()=>window.print();
  document.querySelector('#requestExtension').onclick=()=>{const modal=document.createElement('div');modal.className='modal open';modal.innerHTML='<form class="modal-box"><h3>طلب تمديد المهلة</h3><div class="field"><label>الموعد الجديد</label><input name="dueDate" type="date" required></div><div class="field"><label>سبب الطلب</label><textarea name="reason" rows="3" required></textarea></div><div class="actions"><button class="btn btn-primary">إرسال الطلب</button><button type="button" class="btn btn-light" data-close>إلغاء</button></div></form>';document.body.append(modal);modal.querySelector('[data-close]').onclick=()=>modal.remove();modal.querySelector('form').onsubmit=e=>{e.preventDefault();try{CorrespondenceSystem.requestExtension(type,item.id||item.number,{newDueDate:e.target.dueDate.value,reason:e.target.reason.value});modal.remove();toast('تم إرسال طلب التمديد للاعتماد')}catch(error){toast(error.message,'error')}}};
})();
