(function(){
  const D=window.DemoData||{incoming:[],outgoing:[],internal:[],departments:[],users:[],notifications:[]};
  const page=document.body.dataset.page||'dashboard';
  const svg=(path,cls='')=>`<svg class="${cls}" viewBox="0 0 24 24" aria-hidden="true">${path}</svg>`;
  const icons={dashboard:'<rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/>',inbox:'<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M3 13h5l2 3h4l2-3h5"/>',incoming:'<path d="M12 3v12m-5-5 5 5 5-5M5 21h14"/>',outgoing:'<path d="M12 21V9m-5 5 5-5 5 5M5 3h14"/>',internal:'<path d="M7 7h11l-3-3m3 3-3 3M17 17H6l3 3m-3-3 3-3"/>',compose:'<path d="M12 20h9M16.5 3.5a2.1 2.1 0 013 3L8 18l-4 1 1-4z"/>',archive:'<rect x="3" y="4" width="18" height="5" rx="1"/><path d="M5 9v11h14V9M9 13h6"/>',reports:'<path d="M4 20V10m6 10V4m6 16v-7m6 7H2"/>',departments:'<path d="M4 21V6l8-3 8 3v15M8 9h2m4 0h2m-8 4h2m4 0h2m-6 8v-4h4v4"/>',users:'<circle cx="9" cy="8" r="3"/><path d="M3 20c0-4 2.5-7 6-7s6 3 6 7m7-9h-6m3-3v6"/>',activity:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',settings:'<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 00.3 1.9l.1.1-2.8 2.8-.1-.1a1.7 1.7 0 00-1.9-.3 1.7 1.7 0 00-1 1.6v.2h-4V21a1.7 1.7 0 00-1-1.6 1.7 1.7 0 00-1.9.3l-.1.1L4.2 17l.1-.1a1.7 1.7 0 00.3-1.9A1.7 1.7 0 003 14H2.8v-4H3a1.7 1.7 0 001.6-1 1.7 1.7 0 00-.3-1.9L4.2 7 7 4.2l.1.1a1.7 1.7 0 001.9.3A1.7 1.7 0 0010 3V2.8h4V3a1.7 1.7 0 001 1.6 1.7 1.7 0 001.9-.3l.1-.1L19.8 7l-.1.1a1.7 1.7 0 00-.3 1.9A1.7 1.7 0 0021 10h.2v4H21a1.7 1.7 0 00-1.6 1z"/>',logout:'<path d="M10 17l5-5-5-5m5 5H3m12-8h5v16h-5"/>',menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',search:'<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>',bell:'<path d="M18 8a6 6 0 00-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/>',chevron:'<path d="m9 18 6-6-6-6"/>',user:'<circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0116 0"/>'};
  const meta={dashboard:['لوحة التحكم','dashboard.html'],inbox:['صندوق الوارد الخاص بي','inbox.html'],approvals:['الاعتمادات','approvals.html'],incoming:['البريد الوارد','incoming.html'],outgoing:['البريد الصادر','outgoing.html'],internal:['المراسلات الداخلية','internal.html'],compose:['إنشاء مراسلة','compose.html'],scanner:['مركز المسح الضوئي','scanner.html'],archive:['الأرشيف الإلكتروني','archive.html'],reports:['التقارير','reports.html'],departments:['دليل الأقسام','departments.html'],activity:['سجل العمليات','activity-log.html'],settings:['إعدادات المراسلات','settings.html']};
  document.title=`${meta[page]?.[0]||'تفاصيل المراسلة'} | بلدية المغازي`;
  const statusClass=s=>String(s).includes('متأخر')?'red':String(s).includes('إنجاز')||String(s).includes('إرسال')||String(s).includes('مؤرشف')?'green':String(s).includes('معالجة')||String(s).includes('انتظار')||String(s).includes('تحويل')?'orange':'blue';
  window.badge=s=>`<span class="badge badge-${statusClass(s)}">${s||'غير محدد'}</span>`;
  window.toast=(message,type='success')=>{let t=document.querySelector('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.append(t)}t.className=`toast toast-${type}`;t.textContent=message;requestAnimationFrame(()=>t.classList.add('show'));clearTimeout(window.__toastTimer);window.__toastTimer=setTimeout(()=>t.classList.remove('show'),3200)};
  window.confirmAction=({title='تأكيد الإجراء',message,confirmText='تأكيد',danger=false})=>new Promise(resolve=>{const modal=document.createElement('div');modal.className='modal open';modal.innerHTML=`<div class="modal-box confirm-box" role="dialog" aria-modal="true" aria-labelledby="confirmTitle"><div class="confirm-icon">${svg(danger?icons.activity:icons.archive)}</div><h3 id="confirmTitle">${title}</h3><p>${message}</p><div class="actions"><button class="btn ${danger?'btn-danger':'btn-primary'}" data-confirm>${confirmText}</button><button class="btn btn-light" data-cancel>إلغاء</button></div></div>`;document.body.append(modal);const done=v=>{modal.remove();resolve(v)};modal.querySelector('[data-confirm]').onclick=()=>done(true);modal.querySelector('[data-cancel]').onclick=()=>done(false);modal.onclick=e=>{if(e.target===modal)done(false)}});
  const getData=(key,seed)=>{try{return JSON.parse(localStorage.getItem(key))||seed}catch{return seed}};
  window.AppData={incoming:()=>getData('municipalityIncoming',D.incoming),outgoing:()=>getData('municipalityOutgoing',D.outgoing),internal:()=>getData('municipalityInternal',D.internal)};
  function shell(){
    if(page==='login')return;
    const current=window.AppContext?.currentUser||{name:'مستخدم البلدية',jobTitle:'المسمى الوظيفي',department:'بلدية المغازي'};
    const unread=(window.AppContext?.notifications||[]).filter(n=>!n.read).length||2;
    document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="css/enterprise.css">');
    const nav=Object.entries(meta).map(([key,[label,href]])=>`<a class="${page===key?'active':''}" href="${href}" ${page===key?'aria-current="page"':''}><span class="nav-icon">${svg(icons[key]||icons.archive)}</span><span>${label}</span>${key==='inbox'?'<i class="nav-badge">4</i>':''}</a>`).join('');
    document.body.insertAdjacentHTML('afterbegin',`<div class="sidebar-overlay" id="sidebarOverlay"></div><aside class="sidebar" id="sidebar"><div class="brand"><a href="dashboard.html" class="brand-home"><img class="module-logo" src="assets/images/maghazi-logo.jpeg" alt="شعار بلدية المغازي"><span><b>بلدية المغازي</b><small>نظام المراسلات والأرشيف الإلكتروني</small></span></a><button class="sidebar-collapse" id="sidebarCollapse" aria-label="طي القائمة">${svg(icons.chevron)}</button></div><nav class="nav" aria-label="القائمة الرئيسية">${nav}<div class="nav-separator"></div><a href="login.html" id="logoutLink"><span class="nav-icon">${svg(icons.logout)}</span><span>تسجيل الخروج</span></a></nav></aside><main class="main"><header class="topbar"><div class="top-title"><button class="icon-btn mobile-toggle" id="menu" aria-label="فتح القائمة">${svg(icons.menu)}</button><div><h1>${meta[page]?.[0]||'نظام المراسلات'}</h1><small>نظام المراسلات والأرشيف الإلكتروني</small></div></div><div class="top-actions"><div class="searchbox">${svg(icons.search)}<input id="quickSearch" autocomplete="off" aria-label="البحث العام" placeholder="ابحث برقم الكتاب أو الموضوع أو الجهة..."><div class="dropdown search-results" id="searchDrop"></div></div><div class="notification-wrap"><button class="icon-btn" id="bell" aria-label="الإشعارات" aria-expanded="false">${svg(icons.bell)}<i class="count">${unread}</i></button><div class="dropdown" id="notifications"></div></div><div class="user-menu-wrap"><button class="user" id="userMenuButton" aria-label="قائمة المستخدم" aria-expanded="false"><span class="avatar">${current.name.charAt(0)}</span><span class="user-copy"><b>${current.name}</b><small>${current.jobTitle||current.department||'موظف'}</small></span>${svg(icons.chevron)}</button><div class="dropdown user-dropdown" id="userMenu"><a href="#">${svg(icons.user)} الملف الشخصي</a><a href="settings.html">${svg(icons.settings)} الإعدادات</a><a href="login.html">${svg(icons.logout)} تسجيل الخروج</a></div></div></div></header><section class="content" id="app"></section></main><div class="toast" role="status" aria-live="polite"></div>`);
  }
  function table(rows,cols){return `<div class="table-wrap"><table class="table"><thead><tr>${cols.map(c=>`<th>${c[0]}</th>`).join('')}<th>الإجراء</th></tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${cols.map(c=>`<td>${c[1](r)}</td>`).join('')}<td><a class="btn btn-light btn-sm" href="incoming-details.html?id=${r.id||1}">عرض</a></td></tr>`).join(''):'<tr><td colspan="99"><div class="empty-state">لا توجد نتائج مطابقة</div></td></tr>'}</tbody></table></div>`}
  function head(title,desc,action=''){return `<div class="page-head"><div><span class="page-kicker">بلدية المغازي</span><h2>${title}</h2><div class="muted">${desc}</div></div>${action}</div>`}
  function adminRender(){const app=document.querySelector('#app');if(!app)return;if(page==='departments'){const incoming=AppData.incoming();app.innerHTML=head('الأقسام والدوائر','إدارة الهيكل الإداري ومتابعة أداء الدوائر')+`<div class="department-grid">${D.departments.map((name,i)=>{const items=incoming.filter(r=>r.department===name),late=items.filter(r=>r.status==='متأخر').length,done=items.filter(r=>r.status==='تم الإنجاز'||r.status==='مؤرشف').length,rate=items.length?Math.round(done/items.length*100):0;return `<article class="department-card"><div class="department-head"><span>${svg(icons.departments)}</span><div><h3>${name}</h3><small>${i===0?'مدير البلدية':['محمد أحمد','سارة خالد','أحمد محمد'][i%3]}</small></div>${badge('نشط')}</div><div class="department-stats"><span><b>${3+i}</b><small>موظفون</small></span><span><b>${items.length}</b><small>مراسلات حالية</small></span><span><b class="danger">${late}</b><small>متأخرة</small></span></div><div class="dept-progress"><div><span>نسبة الإنجاز</span><b>${rate}%</b></div><i><em style="width:${rate}%"></em></i></div><button class="btn btn-light department-view" data-department="${name}">عرض التفاصيل</button></article>`}).join('')}</div>`}else if(page==='users'){app.innerHTML=head('المستخدمون والصلاحيات','واجهة إدارة حسابات موظفي البلدية وأدوارهم',`<button class="btn btn-primary" id="newUser">+ إضافة مستخدم</button>`)+`<section class="list-panel"><div class="list-panel-head"><div><h3>دليل المستخدمين</h3><span>${D.users.length} مستخدمين</span></div></div>${table(D.users,[['المستخدم',r=>`<span class="person-cell"><span class="avatar avatar-sm">${r.name[0]}</span><span><b>${r.name}</b><small>${r.email}</small></span></span>`],['المسمى الوظيفي',r=>r.title],['القسم',r=>r.dept],['الدور',r=>badge(r.role)],['الحالة',r=>badge(r.status)],['آخر دخول',()=>'<span class="muted">اليوم 09:31</span>']])}</section>`}else if(page==='settings'){app.innerHTML=head('إعدادات النظام','بيانات بلدية المغازي وخيارات وحدة المراسلات')+`<form class="card settings-form" id="settingsForm"><div class="form-grid"><div class="field span-2"><label>اسم البلدية</label><input name="name" value="بلدية المغازي" readonly></div><div class="field"><label>السنة المالية</label><select name="fiscalYear"><option>2026</option></select></div><div class="field"><label>ترقيم المراسلات</label><select name="numbering"><option>سنوي</option></select></div><div class="field span-2"><label>البريد الرسمي</label><input name="email" type="email" placeholder="البريد الرسمي للبلدية"></div><div class="field span-2"><label>العنوان</label><input name="address" value="مخيم المغازي – فلسطين"></div></div><div class="form-actions-inline"><button class="btn btn-primary">حفظ الإعدادات</button></div></form>`}}
  function render(){if(['departments','users','settings'].includes(page))adminRender()}
  function allSearchData(){return [...AppData.incoming().map(x=>({...x,type:'وارد',party:x.sender,href:`incoming-details.html?id=${x.id}`})),...AppData.outgoing().map(x=>({...x,type:'صادر',party:x.to,href:'outgoing.html'})),...AppData.internal().map(x=>({...x,type:'داخلي',party:x.from,href:'internal.html'}))]}
  window.CorrespondenceSystem?.processDeadlines();
  shell();render();
  const appRoot=document.querySelector('#app');
  if(appRoot&&!appRoot.children.length){appRoot.innerHTML=`<div class="page-loading" role="status" aria-live="polite" aria-label="جاري تحميل الصفحة"><div class="loading-head"><i></i><span></span></div><div class="loading-kpis"><i></i><i></i><i></i><i></i></div><div class="loading-panel"><span></span><span></span><span></span><span></span><span></span></div></div>`}
  const profileLink=document.querySelector('#userMenu a[href="#"]');
  if(profileLink)profileLink.href='settings.html';
  const fallbackNotifications=document.querySelector('#notifications');if(fallbackNotifications&&!fallbackNotifications.children.length){fallbackNotifications.innerHTML=`<div class="employee-notif-head"><b>إشعارات المراسلات</b></div><div class="employee-notif-list">${(window.AppContext?.notifications||[]).map(n=>`<a class="employee-notif ${n.read?'':'unread'}" href="inbox.html"><span><b>${n.title}</b><small>${n.details}</small><em>${n.time}</em></span></a>`).join('')||'<div class="empty-state compact">لا توجد إشعارات</div>'}</div><a class="employee-notif-footer" href="inbox.html">عرض صندوق الموظف</a>`}
  document.addEventListener('click',async e=>{const sidebar=document.querySelector('#sidebar');if(e.target.closest('#menu')){sidebar?.classList.add('open');document.querySelector('#sidebarOverlay')?.classList.add('open')}if(e.target.closest('#sidebarOverlay')){sidebar?.classList.remove('open');e.target.classList.remove('open')}if(e.target.closest('#sidebarCollapse'))document.body.classList.toggle('sidebar-collapsed');const bell=e.target.closest('#bell');if(bell){const menu=document.querySelector('#notifications'),open=menu.classList.toggle('open');bell.setAttribute('aria-expanded',open)}const userButton=e.target.closest('#userMenuButton');if(userButton){const menu=document.querySelector('#userMenu'),open=menu.classList.toggle('open');userButton.setAttribute('aria-expanded',open)}if(!e.target.closest('.notification-wrap'))document.querySelector('#notifications')?.classList.remove('open');if(!e.target.closest('.user-menu-wrap'))document.querySelector('#userMenu')?.classList.remove('open');if(e.target.closest('#logoutLink')){e.preventDefault();if(await confirmAction({title:'تسجيل الخروج',message:'هل تريد إنهاء جلسة العمل الحالية؟',confirmText:'تسجيل الخروج'}))location.href='login.html'}if(e.target.closest('.department-view'))toast('تفاصيل القسم متاحة للعرض ضمن بطاقة القسم');if(e.target.closest('#newUser'))toast('إضافة المستخدم تتطلب ربط نظام المستخدمين في بوابة البلدية','info');if(e.target.closest('#settingsForm button')){e.preventDefault();toast('تم حفظ إعدادات الواجهة')}});
  document.addEventListener('input',e=>{if(e.target.id!=='quickSearch')return;const q=e.target.value.trim().toLowerCase(),drop=document.querySelector('#searchDrop');if(q.length<2){drop.classList.remove('open');return}const result=allSearchData().filter(x=>[x.number,x.subject,x.party].some(v=>String(v||'').toLowerCase().includes(q))).slice(0,7);drop.innerHTML=result.length?result.map(x=>`<a class="search-result" href="${x.href}"><span class="search-result-type">${x.type}</span><span><b>${x.number} · ${x.subject}</b><small>${x.party||'—'}</small></span>${badge(x.status)}</a>`).join(''):'<div class="empty-state compact">لا توجد نتائج مطابقة</div>';drop.classList.add('open')});
})();
