(function(){
  if(document.body.dataset.page!=='scanner')return;
  const app=document.querySelector('#app'),items=[];
  const svg=path=>`<svg viewBox="0 0 24 24" aria-hidden="true">${path}</svg>`,I={scan:'<path d="M7 3h10v5H7zM5 14h14v7H5z"/><path d="M5 17H3V9h18v8h-2M17 12h1"/>',upload:'<path d="M12 16V4m-4 4 4-4 4 4M4 20h16"/>',camera:'<path d="M4 7h4l2-3h4l2 3h4v13H4z"/><circle cx="12" cy="13" r="4"/>'};
  app.innerHTML=`<section class="list-page-head"><div><span class="pro-eyebrow">الديوان · إدخال الوثائق</span><h2>مركز المسح الضوئي</h2><p>تجميع صفحات الكتاب، مراجعتها، ثم إرسالها إلى نموذج تسجيل الوارد.</p></div><a class="btn btn-light" href="incoming.html">العودة إلى الوارد</a></section><div class="scanner-grid"><section class="scan-panel"><h3>مصدر الوثيقة</h3><div class="scan-source"><label>${svg(I.upload)}<b>رفع PDF أو صور</b><small>من الجهاز أو مجلد السكانر</small><input id="scanFiles" type="file" multiple accept=".pdf,.jpg,.jpeg,.png,.tif,.tiff"></label><label>${svg(I.camera)}<b>التقاط بالكاميرا</b><small>مناسب للهاتف والجهاز اللوحي</small><input id="cameraFiles" type="file" multiple accept="image/*" capture="environment"></label><button id="hardwareScan">${svg(I.scan)}<b>المسح من الجهاز</b><small>يتطلب خدمة الربط المحلية</small></button></div><div class="scan-queue-head"><div><h3>صفحات الدفعة</h3><small id="queueCount">لا توجد صفحات</small></div><button class="btn btn-light btn-sm" id="clearQueue">حذف جميع الصفحات</button></div><div class="scan-queue" id="scanQueue"></div></section><aside class="scan-side"><h3>إعدادات المعالجة</h3><p>تُطبق عند إرسال الدفعة إلى الخادم.</p><div class="scan-options"><div class="field"><label>جودة المسح</label><select id="scanQuality"><option value="300">300 DPI — وثائق رسمية</option><option value="200">200 DPI — حجم متوسط</option><option value="150">150 DPI — معاينة</option></select></div><div class="field"><label>نمط الألوان</label><select id="scanColor"><option>ألوان</option><option>تدرج رمادي</option><option>أبيض وأسود</option></select></div><label class="scan-toggle"><input id="scanOcr" type="checkbox" checked><span><b>التعرف على النص OCR</b><small>للبحث داخل الوثيقة بعد ربط خدمة المعالجة.</small></span></label><label class="scan-toggle"><input id="scanPdf" type="checkbox" checked><span><b>دمج الصفحات في PDF</b><small>إنشاء ملف واحد مرتب للكتاب.</small></span></label></div><div class="scan-summary"><div><span>عدد الملفات</span><b id="summaryCount">0</b></div><div><span>الحجم الإجمالي</span><b id="summarySize">0 MB</b></div><div><span>الحالة</span><b id="summaryStatus">بانتظار الملفات</b></div></div><div class="scan-actions"><button class="btn btn-primary" id="createIncoming" disabled>متابعة إلى تسجيل الوارد</button><button class="btn btn-light" id="saveBatch" disabled>حفظ دفعة المسح</button></div><div class="scan-note">التشغيل المباشر لجهاز Scanner مكتبي يحتاج خدمة محلية آمنة أو إعداد الجهاز للإرسال إلى مجلد مراقب. الواجهة لا تدّعي تشغيل الجهاز قبل هذا الربط.</div></aside></div>`;
  const queue=document.querySelector('#scanQueue'),format=bytes=>bytes<1048576?`${Math.ceil(bytes/1024)} KB`:`${(bytes/1048576).toFixed(1)} MB`;
  function addFiles(files){[...files].forEach(file=>{if(!/pdf|image/.test(file.type)&&!/\.(tif|tiff)$/i.test(file.name)){toast(`الملف ${file.name} غير مدعوم`,'error');return}if(file.size>20*1024*1024){toast(`الملف ${file.name} أكبر من 20MB`,'error');return}items.push({id:Date.now()+Math.random(),file,rotation:0,url:file.type.startsWith('image/')?URL.createObjectURL(file):null})});render()}
  function render(){queue.innerHTML=items.length?items.map((item,index)=>`<article class="scan-page" data-id="${item.id}"><div class="scan-preview">${item.url?`<img src="${item.url}" alt="معاينة الصفحة ${index+1}" style="transform:rotate(${item.rotation}deg)">`:'<span class="scan-pdf">ملف PDF</span>'}</div><div class="scan-page-actions"><button data-rotate title="تدوير">↻</button><button data-remove title="حذف">×</button></div><footer><b>${index+1}. ${item.file.name}</b><small>${format(item.file.size)}</small></footer></article>`).join(''):'<div class="scan-empty">أضف ملفات PDF أو صورًا لتكوين دفعة المسح</div>';const total=items.reduce((sum,x)=>sum+x.file.size,0);document.querySelector('#queueCount').textContent=items.length?`${items.length} ملفات في الدفعة`:'لا توجد صفحات';document.querySelector('#summaryCount').textContent=items.length;document.querySelector('#summarySize').textContent=format(total);document.querySelector('#summaryStatus').textContent=items.length?'جاهزة للمراجعة':'بانتظار الملفات';document.querySelector('#createIncoming').disabled=!items.length;document.querySelector('#saveBatch').disabled=!items.length}
  document.querySelector('#scanFiles').onchange=e=>addFiles(e.target.files);document.querySelector('#cameraFiles').onchange=e=>addFiles(e.target.files);
  queue.onclick=e=>{const card=e.target.closest('.scan-page');if(!card)return;const item=items.find(x=>String(x.id)===card.dataset.id);if(e.target.closest('[data-remove]')){if(item.url)URL.revokeObjectURL(item.url);items.splice(items.indexOf(item),1);render()}if(e.target.closest('[data-rotate]')){item.rotation=(item.rotation+90)%360;render()}};
  document.querySelector('#clearQueue').onclick=async()=>{if(!items.length){toast('لا توجد صفحات لحذفها','info');return}if(!(await confirmAction({title:'حذف جميع الصفحات',message:'سيتم حذف جميع الملفات الموجودة في دفعة المسح الحالية.',confirmText:'حذف الصفحات',danger:true})))return;items.forEach(x=>x.url&&URL.revokeObjectURL(x.url));items.length=0;render();toast('تم حذف جميع الصفحات')};
  document.querySelector('#hardwareScan').onclick=()=>toast('تشغيل السكانر يحتاج تثبيت خدمة الربط المحلية أو إعداد Scan-to-Folder','info');
  document.querySelector('#saveBatch').onclick=()=>{const batch={id:Date.now(),createdAt:new Date().toISOString(),files:items.map(x=>({name:x.file.name,size:x.file.size,type:x.file.type,rotation:x.rotation})),quality:document.querySelector('#scanQuality').value,color:document.querySelector('#scanColor').value,ocr:document.querySelector('#scanOcr').checked,mergePdf:document.querySelector('#scanPdf').checked};localStorage.setItem('municipalityScanDraft',JSON.stringify(batch));CorrespondenceSystem.audit('حفظ دفعة مسح ضوئي',{id:batch.id,files:batch.files.length});toast('تم حفظ بيانات دفعة المسح محليًا؛ رفع الملفات الدائم يحتاج الخادم')};
  document.querySelector('#createIncoming').onclick=()=>{const batch={id:Date.now(),files:items.map(x=>({name:x.file.name,size:x.file.size,type:x.file.type,rotation:x.rotation})),ocr:document.querySelector('#scanOcr').checked};sessionStorage.setItem('municipalityIncomingScanBatch',JSON.stringify(batch));CorrespondenceSystem.audit('إرسال دفعة مسح إلى تسجيل الوارد',{id:batch.id,files:batch.files.length});location.href='incoming-add.html?source=scanner'};
  render();
})();
