const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const store=new Map();
global.localStorage={getItem:key=>store.has(key)?store.get(key):null,setItem:(key,value)=>store.set(key,String(value)),removeItem:key=>store.delete(key)};
global.window=global;
vm.runInThisContext(fs.readFileSync(require('node:path').join(__dirname,'..','js','data.js'),'utf8'));
const record=CorrespondenceSystem.create('outgoing',{id:'test-approval',number:'مسودة-test',subject:'اختبار مسار الاعتماد',status:'بانتظار التدقيق',department:'الديوان',to:'جهة اختبار'});
assert.equal(record.status,'بانتظار التدقيق');
assert.equal(CorrespondenceSystem.approve('outgoing',record.id).status,'بانتظار الاعتماد');
assert.equal(CorrespondenceSystem.approve('outgoing',record.id).status,'معتمدة');
CorrespondenceSystem.requestExtension('outgoing',record.id,{newDueDate:'2099-12-31',reason:'اختبار التمديد'});
assert.equal(CorrespondenceSystem.find('outgoing',record.id).extensionRequest.status,'بانتظار الموافقة');
CorrespondenceSystem.decideExtension('outgoing',record.id,true,'موافق');
assert.equal(CorrespondenceSystem.find('outgoing',record.id).dueDate,'2099-12-31');
assert.equal(CorrespondenceSystem.sla(CorrespondenceSystem.find('outgoing',record.id)).state,'on-time');
assert.ok(CorrespondenceSystem.auditLog().length>=5);
console.log('System core workflow test passed.');
