import { useMemo, useState } from 'react';
import { Check, CheckCircle2, Clock3, Eye, FileCheck2, FileSearch, Filter, History, MessageSquareText, RotateCcw, Search, ShieldCheck, TimerReset, X } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { Modal, PageHead, Status } from './components';
import { label, useStore } from './store';
import type { Mail } from './types';

type ApprovalTab='all'|'review'|'approval'|'extension'|'returned'|'approved';
const stage=(mail:Mail):ApprovalTab=>mail.extensionRequested?'extension':mail.status==='بانتظار التدقيق'?'review':mail.status==='بانتظار الاعتماد'?'approval':mail.status==='معاد للتعديل'?'returned':['معتمدة','تم الإرسال','تم الإنجاز','مؤرشف'].includes(mail.status)?'approved':'review';
const stageLabel=(value:ApprovalTab)=>({all:'جميع الطلبات',review:'بانتظار التدقيق',approval:'بانتظار الاعتماد',extension:'طلبات التمديد',returned:'معادة للتعديل',approved:'معتمدة'}[value]);

export function ApprovalCenter(){
  const mail=useStore(s=>s.mail),update=useStore(s=>s.updateMail),navigate=useNavigate();
  const candidates=useMemo(()=>mail.filter(m=>m.type!=='incoming'&&!m.archived),[mail]);
  const [tab,setTab]=useState<ApprovalTab>('all'),[query,setQuery]=useState(''),[priority,setPriority]=useState(''),[selected,setSelected]=useState<Mail|null>(null),[decisionNote,setDecisionNote]=useState('');
  const tabs:ApprovalTab[]=['all','review','approval','extension','returned','approved'];
  const rows=candidates.filter(m=>tab==='all'||stage(m)===tab).filter(m=>!priority||m.priority===priority).filter(m=>!query||[m.number,m.subject,m.to,m.department,m.employee].some(v=>v.includes(query)));
  const decide=(action:'approve'|'return'|'reject')=>{if(!selected)return;if(action!=='approve'&&!decisionNote.trim())return alert('اكتبي سبب القرار');const current=stage(selected);const status=action==='approve'?(current==='review'?'بانتظار الاعتماد':current==='extension'?selected.status:'معتمدة'):action==='return'?'معاد للتعديل':'ملغي';const changes:Partial<Mail>={status};if(current==='extension')changes.extensionRequested=false;update(selected.id,{...changes,notes:[...selected.notes,{id:crypto.randomUUID(),author:'مسؤول الاعتماد',text:`قرار ${action==='approve'?'الموافقة':action==='return'?'الإعادة للتعديل':'الرفض'}: ${decisionNote||'تمت المراجعة والموافقة'}`,time:new Date().toISOString()}]},action==='approve'?'اعتماد الطلب':action==='return'?'إعادة الطلب للتعديل':'رفض الطلب');setSelected(null);setDecisionNote('')};
  return <>
    <PageHead title="صندوق الاعتمادات" subtitle="تدقيق الكتب واعتمادها وإعادتها للتعديل والبت في طلبات تمديد المهلة"/>
    <div className="approval-kpis">{[['بانتظار التدقيق','review',FileSearch],['بانتظار الاعتماد','approval',ShieldCheck],['طلبات التمديد','extension',TimerReset],['معتمدة','approved',CheckCircle2]].map(([title,key,Icon])=><button key={String(key)} onClick={()=>setTab(key as ApprovalTab)}><i><Icon/></i><span><small>{String(title)}</small><b>{candidates.filter(m=>stage(m)===key).length}</b></span></button>)}</div>
    <div className="approval-layout">
      <aside className="panel approval-nav"><h3>تصنيفات الطلبات</h3>{tabs.map(value=><button className={tab===value?'active':''} key={value} onClick={()=>setTab(value)}><span>{stageLabel(value)}</span><b>{value==='all'?candidates.length:candidates.filter(m=>stage(m)===value).length}</b></button>)}<div className="approval-policy"><ShieldCheck/><b>ضوابط الاعتماد</b><p>كل قرار يُحفظ باسم المستخدم وتاريخه داخل سجل العمليات.</p></div></aside>
      <main>
        <div className="approval-filters"><div><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="بحث برقم الكتاب أو الموضوع أو الجهة..."/></div><select value={priority} onChange={e=>setPriority(e.target.value)}><option value="">جميع الأولويات</option><option>عاجل جداً</option><option>عاجل</option><option>عادي</option></select><button className="secondary"><Filter/> تصفية</button></div>
        <section className="panel approval-requests"><div className="panel-head"><div><h2>{stageLabel(tab)}</h2><p>{rows.length} طلبات ظاهرة</p></div><button className="secondary" onClick={()=>location.reload()}><RotateCcw/> تحديث</button></div>{rows.length?rows.map(m=><article key={m.id}><div className="request-icon"><FileCheck2/></div><div className="request-main"><div><span>{label(m.type)} · {m.number}</span><Status>{stageLabel(stage(m))}</Status></div><h3>{m.subject}</h3><p>{m.to} · {m.department||'غير محدد'} · أعدها {m.employee||'مستخدم البلدية'}</p><div className="request-meta"><span><Clock3/> {m.date}</span><span className={`priority p-${m.priority.replaceAll(' ','-')}`}>{m.priority}</span>{m.dueDate&&<span><TimerReset/> المهلة {m.dueDate}</span>}</div></div><div className="request-actions"><button title="عرض المراسلة" onClick={()=>navigate(`/app/mail/${m.id}`)}><Eye/></button><button className="primary" onClick={()=>setSelected(m)}>مراجعة الطلب</button></div></article>):<div className="approval-empty"><CheckCircle2/><h3>لا توجد طلبات في هذا التصنيف</h3><p>ستظهر الطلبات هنا عند إرسالها للتدقيق أو الاعتماد.</p></div>}</section>
      </main>
    </div>
    {selected&&<Modal title="مراجعة واتخاذ القرار" onClose={()=>setSelected(null)}><div className="decision-summary"><div><small>{selected.number} · {label(selected.type)}</small><h3>{selected.subject}</h3><p>{selected.to} · {selected.department}</p></div><Status>{stageLabel(stage(selected))}</Status></div><div className="decision-checks"><h4>قائمة التحقق قبل الاعتماد</h4><label><input type="checkbox" defaultChecked/> تدقيق بيانات الجهة والموضوع</label><label><input type="checkbox" defaultChecked/> التأكد من المرفقات وصحة النسخة</label><label><input type="checkbox" defaultChecked/> مراجعة مسار التحويل والصلاحيات</label></div><label className="decision-note">ملاحظات القرار<textarea value={decisionNote} onChange={e=>setDecisionNote(e.target.value)} placeholder="مطلوبة عند الإعادة أو الرفض..."/></label><div className="decision-actions"><button className="reject" onClick={()=>decide('reject')}><X/> رفض</button><button className="return" onClick={()=>decide('return')}><MessageSquareText/> إعادة للتعديل</button><button className="approve" onClick={()=>decide('approve')}><Check/> اعتماد ومتابعة</button></div></Modal>}
  </>;
}
