import type {Audit,Department,Mail,Notification} from './types';
const a=[{id:'a1',name:'كتاب_وزارة_الحكم_المحلي.pdf',size:'2.3 MB'}];
export const seedMail:Mail[]=[
 {id:'145',type:'incoming',number:'145/2026',date:'2026-08-17',from:'وزارة الحكم المحلي',to:'بلدية المغازي',subject:'اعتماد مخطط شبكة الشوارع',department:'دائرة الهندسة',employee:'م. أحمد محمد',priority:'عاجل',status:'قيد المعالجة',dueDate:'2026-08-27',requiresBrief:true,requiresClosure:true,copies:['الديوان'],read:false,attachments:a,notes:[],workflow:[{id:'w1',from:'الديوان',to:'دائرة الهندسة',action:'للدراسة والإفادة',time:'2026-08-17T10:18:00',status:'مفتوح'}]},
 {id:'144',type:'incoming',number:'144/2026',date:'2026-08-17',from:'وزارة المالية',to:'بلدية المغازي',subject:'تعزيز مخصصات الموازنة السنوية',department:'الدائرة المالية',employee:'سارة خالد',priority:'عادي',status:'جديد',read:false,attachments:[],notes:[],workflow:[]},
 {id:'143',type:'incoming',number:'143/2026',date:'2026-08-16',from:'سلطة جودة البيئة',to:'بلدية المغازي',subject:'تقرير تقييم الأثر البيئي',department:'الصحة والبيئة',employee:'رامي عادل',priority:'عاجل جداً',status:'متأخر',dueDate:'2026-08-20',urgentReply:true,requiresBrief:true,read:true,attachments:[],notes:[],workflow:[]},
 {id:'142',type:'incoming',number:'142/2026',date:'2026-08-16',from:'وزارة الأشغال العامة',to:'بلدية المغازي',subject:'صيانة الطريق الرئيسي',department:'دائرة الهندسة',employee:'ليلى حسن',priority:'عاجل',status:'بانتظار الرد',read:true,attachments:[],notes:[],workflow:[]},
 {id:'141',type:'incoming',number:'141/2026',date:'2026-08-15',from:'ديوان الموظفين العام',to:'بلدية المغازي',subject:'تحديث الهيكل التنظيمي',department:'الشؤون الإدارية',employee:'محمد أحمد',priority:'عادي',status:'تم الإنجاز',read:true,attachments:[],notes:[],workflow:[]},
 {id:'88',type:'outgoing',number:'88/2026',date:'2026-08-17',sentAt:'2026-08-17T09:15:00',viewedAt:'2026-08-17T11:32:00',from:'بلدية المغازي',to:'وزارة الحكم المحلي',subject:'طلب اعتماد مشروع تأهيل الطرق',department:'المشاريع',employee:'محمود يوسف',priority:'عادي',status:'تم الإرسال',read:true,attachments:[],notes:[],workflow:[]},
 {id:'87',type:'outgoing',number:'87/2026',date:'2026-08-16',sentAt:'2026-08-16T12:40:00',from:'بلدية المغازي',to:'سلطة المياه',subject:'متابعة مشروع شبكة المياه',department:'المياه والصرف الصحي',employee:'عمر جمال',priority:'عاجل',status:'بانتظار الرد',read:true,attachments:[],notes:[],workflow:[]},
 {id:'i32',type:'internal',number:'د-32/2026',date:'2026-08-17',from:'رئيس البلدية',to:'جميع الأقسام',subject:'الالتزام بساعات الدوام',department:'الشؤون الإدارية',employee:'مستخدم البلدية',priority:'عادي',status:'جديد',read:false,attachments:[],notes:[],workflow:[]},
 {id:'i31',type:'internal',number:'د-31/2026',date:'2026-08-16',from:'المدير العام',to:'دائرة الهندسة',subject:'متابعة مشروع السوق المركزي',department:'دائرة الهندسة',employee:'م. أحمد محمد',priority:'عاجل',status:'قيد المعالجة',read:true,attachments:[],notes:[],workflow:[]}
];
export const departments:Department[]=[['الديوان','محمد أحمد',4],['دائرة الهندسة','سليم النجار',12],['الدائرة المالية','سارة خالد',7],['الشؤون الإدارية','ليلى حسن',8],['الصحة والبيئة','رامي عادل',10],['المشاريع','محمود يوسف',6],['العلاقات العامة','نور خليل',5],['تكنولوجيا المعلومات','وسام علي',4]].map((d,i)=>({id:String(i+1),name:String(d[0]),manager:String(d[1]),employees:Number(d[2]),active:true}));
export const seedNotifications:Notification[]=[{id:'n1',title:'وصلتك مراسلة جديدة',details:'الكتاب 145/2026 من الديوان',time:'منذ 5 دقائق',read:false,mailId:'145'},{id:'n2',title:'مراسلة تحتاج متابعة',details:'المراسلة 143/2026 متأخرة',time:'منذ ساعة',read:false,mailId:'143'},{id:'n3',title:'تم إنجاز معاملة',details:'أُنجز الكتاب 141/2026',time:'أمس',read:true,mailId:'141'}];
export const seedAudit:Audit[]=[{id:'e1',action:'تسجيل كتاب وارد',details:'سجّل كتاباً وارداً جديداً',user:'محمد أحمد',number:'145/2026',time:'2026-08-17T10:18:00'},{id:'e2',action:'تحديث الحالة',details:'تم تحديث حالة الكتاب إلى تم الإنجاز',user:'سارة خالد',number:'141/2026',time:'2026-08-17T09:55:00'},{id:'e3',action:'تسجيل الدخول',details:'دخول ناجح إلى نظام المراسلات',user:'مستخدم البلدية',time:'2026-08-17T09:31:00'}];
export const departmentNames=departments.map(x=>x.name);
