import {useMemo,useState} from 'react';
import {Building2,Mail,MapPin,Pencil,Phone,Plus,Search,Trash2,Users} from 'lucide-react';
import {Modal,PageHead,Status} from './components';
import {departmentNames} from './data';
export type DirectoryEntity={id:string;name:string;category:string;email:string;phone:string;address:string;active:boolean};
export type DistributionGroup={id:string;name:string;members:string[];purpose:string;active:boolean};
const emptyEntity={name:'',category:'وزارة',email:'',phone:'',address:''},emptyGroup={name:'',purpose:'',members:[] as string[]};
const seedEntities:DirectoryEntity[]=[{id:'e1',name:'وزارة الحكم المحلي',category:'وزارة',email:'info@molg.pna.ps',phone:'',address:'رام الله',active:true},{id:'e2',name:'وزارة المالية',category:'وزارة',email:'info@mof.pna.ps',phone:'',address:'رام الله',active:true},{id:'e3',name:'سلطة المياه الفلسطينية',category:'سلطة حكومية',email:'info@pwa.ps',phone:'',address:'رام الله',active:true},{id:'e4',name:'سلطة جودة البيئة',category:'سلطة حكومية',email:'info@environment.ps',phone:'',address:'فلسطين',active:true},{id:'e5',name:'وزارة الأشغال العامة والإسكان',category:'وزارة',email:'info@mpwh.pna.ps',phone:'',address:'رام الله',active:true}];
const seedGroups:DistributionGroup[]=[{id:'g1',name:'مديرو الدوائر',members:['الدائرة الفنية','الشؤون الإدارية والمالية','الصحة والمياه والصرف الصحي'],purpose:'التعاميم والقرارات الإدارية',active:true},{id:'g2',name:'لجنة الطوارئ',members:['رئيس البلدية','الديوان','الصحة والبيئة','الأشغال العامة'],purpose:'مراسلات الطوارئ العاجلة',active:true},{id:'g3',name:'جميع الأقسام',members:departmentNames,purpose:'التعاميم العامة',active:true}];
export const getDirectoryEntities=():DirectoryEntity[]=>{try{return JSON.parse(localStorage.getItem('municipality-directory-entities')||JSON.stringify(seedEntities))}catch{return seedEntities}};
export const getDistributionGroups=():DistributionGroup[]=>{try{return JSON.parse(localStorage.getItem('municipality-distribution-groups')||JSON.stringify(seedGroups))}catch{return seedGroups}};
export function CorrespondenceDirectory(){
 const [tab,setTab]=useState<'entities'|'groups'>('entities'),[q,setQ]=useState(''),[entities,setEntities]=useState(getDirectoryEntities),[groups,setGroups]=useState(getDistributionGroups),[entityModal,setEntityModal]=useState(false),[groupModal,setGroupModal]=useState(false),[editingEntity,setEditingEntity]=useState<string|null>(null),[editingGroup,setEditingGroup]=useState<string|null>(null),[confirmDelete,setConfirmDelete]=useState<{kind:'entity'|'group';id:string;name:string}|null>(null),[error,setError]=useState('');
 const [entity,setEntity]=useState(emptyEntity),[group,setGroup]=useState(emptyGroup);
 const filtered=useMemo(()=>entities.filter(x=>!q||[x.name,x.category,x.email].some(v=>v.includes(q))),[entities,q]);
 const saveEntities=(next:DirectoryEntity[])=>{setEntities(next);localStorage.setItem('municipality-directory-entities',JSON.stringify(next))},saveGroups=(next:DistributionGroup[])=>{setGroups(next);localStorage.setItem('municipality-distribution-groups',JSON.stringify(next))};
 const openEntity=(item?:DirectoryEntity)=>{setEditingEntity(item?.id||null);setEntity(item?{name:item.name,category:item.category,email:item.email,phone:item.phone,address:item.address}:emptyEntity);setError('');setEntityModal(true)},openGroup=(item?:DistributionGroup)=>{setEditingGroup(item?.id||null);setGroup(item?{name:item.name,purpose:item.purpose,members:[...item.members]}:emptyGroup);setError('');setGroupModal(true)};
 const submitEntity=()=>{const name=entity.name.trim(),email=entity.email.trim();if(!name)return setError('اسم الجهة مطلوب.');if(entities.some(x=>x.id!==editingEntity&&x.name.trim()===name))return setError('هذه الجهة موجودة مسبقًا.');if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return setError('صيغة البريد الإلكتروني غير صحيحة.');editingEntity?saveEntities(entities.map(x=>x.id===editingEntity?{...x,...entity,name,email}:x)):saveEntities([{...entity,name,email,id:crypto.randomUUID(),active:true},...entities]);setEntityModal(false)};
 const submitGroup=()=>{const name=group.name.trim();if(!name||!group.members.length)return setError('أدخلي اسم المجموعة واختاري عضوًا واحدًا على الأقل.');if(groups.some(x=>x.id!==editingGroup&&x.name.trim()===name))return setError('مجموعة التوزيع موجودة مسبقًا.');editingGroup?saveGroups(groups.map(x=>x.id===editingGroup?{...x,...group,name}:x)):saveGroups([{...group,name,id:crypto.randomUUID(),active:true},...groups]);setGroupModal(false)};
 const remove=()=>{if(!confirmDelete)return;confirmDelete.kind==='entity'?saveEntities(entities.filter(x=>x.id!==confirmDelete.id)):saveGroups(groups.filter(x=>x.id!==confirmDelete.id));setConfirmDelete(null)};
 return <><PageHead title="دليل الجهات والتوزيع" subtitle="مرجع مركزي للوزارات والمؤسسات ومجموعات المستلمين المستخدمة في المراسلات"/><div className="directory-tabs"><button className={tab==='entities'?'active':''} onClick={()=>setTab('entities')}><Building2/> الجهات الخارجية</button><button className={tab==='groups'?'active':''} onClick={()=>setTab('groups')}><Users/> مجموعات التوزيع</button></div>{tab==='entities'?<><section className="panel directory-tools"><div className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحث باسم الجهة أو التصنيف أو البريد..."/></div><button className="primary" onClick={()=>openEntity()}><Plus/> إضافة جهة</button></section><section className="directory-grid">{filtered.map(item=><article className="panel" key={item.id}><div className="directory-card-head"><Building2/><Status>{item.active?'نشطة':'موقوفة'}</Status></div><small>{item.category}</small><h2>{item.name}</h2><p><Mail/> {item.email||'لا يوجد بريد مسجل'}</p><p><Phone/> {item.phone||'لا يوجد هاتف مسجل'}</p><p><MapPin/> {item.address||'لا يوجد عنوان مسجل'}</p><div className="directory-actions"><button className="secondary" onClick={()=>saveEntities(entities.map(x=>x.id===item.id?{...x,active:!x.active}:x))}>{item.active?'إيقاف':'تفعيل'}</button><button className="icon" title="تعديل" onClick={()=>openEntity(item)}><Pencil/></button><button className="icon danger" title="حذف" onClick={()=>setConfirmDelete({kind:'entity',id:item.id,name:item.name})}><Trash2/></button></div></article>)}</section></>:<><section className="panel directory-tools"><div><h2>مجموعات التوزيع المعتمدة</h2><p>اختيار مجموعة يضيفها كمستلم واحد مع حفظ أعضائها إداريًا.</p></div><button className="primary" onClick={()=>openGroup()}><Plus/> مجموعة جديدة</button></section><section className="panel groups-list">{groups.map(item=><article key={item.id}><div className="group-badge"><Users/></div><div><small>{item.purpose}</small><h3>{item.name}</h3><p>{item.members.join('، ')}</p></div><b>{item.members.length} أعضاء</b><Status>{item.active?'فعالة':'موقوفة'}</Status><div className="group-actions"><button className="icon" title="تعديل" onClick={()=>openGroup(item)}><Pencil/></button><button className="icon danger" title="حذف" onClick={()=>setConfirmDelete({kind:'group',id:item.id,name:item.name})}><Trash2/></button></div></article>)}</section></>}
 {entityModal&&<Modal title={editingEntity?'تعديل بيانات الجهة':'إضافة جهة خارجية'} onClose={()=>setEntityModal(false)}><div className="directory-form"><label>اسم الجهة<input value={entity.name} onChange={e=>{setEntity({...entity,name:e.target.value});setError('')}}/></label><label>التصنيف<select value={entity.category} onChange={e=>setEntity({...entity,category:e.target.value})}>{['وزارة','سلطة حكومية','بلدية','مؤسسة أهلية','شركة'].map(x=><option key={x}>{x}</option>)}</select></label><label>البريد الإلكتروني<input type="email" value={entity.email} onChange={e=>{setEntity({...entity,email:e.target.value});setError('')}}/></label><label>الهاتف<input value={entity.phone} onChange={e=>setEntity({...entity,phone:e.target.value})}/></label><label className="wide">العنوان<input value={entity.address} onChange={e=>setEntity({...entity,address:e.target.value})}/></label></div>{error&&<p className="form-error">{error}</p>}<div className="actions"><button className="secondary" onClick={()=>setEntityModal(false)}>إلغاء</button><button className="primary" onClick={submitEntity}>{editingEntity?'حفظ التعديلات':'حفظ الجهة'}</button></div></Modal>}
 {groupModal&&<Modal title={editingGroup?'تعديل مجموعة التوزيع':'إنشاء مجموعة توزيع'} onClose={()=>setGroupModal(false)}><div className="directory-form"><label>اسم المجموعة<input value={group.name} onChange={e=>{setGroup({...group,name:e.target.value});setError('')}}/></label><label>الغرض<input value={group.purpose} onChange={e=>setGroup({...group,purpose:e.target.value})}/></label><div className="wide member-picker">{departmentNames.map(x=><label key={x}><input type="checkbox" checked={group.members.includes(x)} onChange={e=>{setGroup({...group,members:e.target.checked?[...group.members,x]:group.members.filter(m=>m!==x)});setError('')}}/>{x}</label>)}</div></div>{error&&<p className="form-error">{error}</p>}<div className="actions"><button className="secondary" onClick={()=>setGroupModal(false)}>إلغاء</button><button className="primary" onClick={submitGroup}>{editingGroup?'حفظ التعديلات':'حفظ المجموعة'}</button></div></Modal>}
 {confirmDelete&&<Modal title="تأكيد الحذف" onClose={()=>setConfirmDelete(null)}><div className="delete-confirm"><Trash2/><div><b>حذف «{confirmDelete.name}»؟</b><p>لن تتأثر المراسلات السابقة المرتبطة بهذا السجل.</p></div></div><div className="actions"><button className="secondary" onClick={()=>setConfirmDelete(null)}>إلغاء</button><button className="danger-button" onClick={remove}>تأكيد الحذف</button></div></Modal>}</>;
}
