import { useMemo, useState, type CSSProperties } from 'react';
import { AlertTriangle, ArrowDown, ArrowUp, CalendarClock, CheckCircle2, Clock3, Eye, FileInput, FileOutput, Inbox, RotateCcw, Siren, TrendingUp } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { PageHead, Status, deadlineState } from './components';
import { useStore } from './store';
import { comparison, getDashboardStatistics, getDepartmentPerformance, getDueTodayCorrespondence, getOverdueCorrespondence, getPeriodRange, getPriorityCorrespondence, getTimeSeries, isCompleted, previousRange, type AnalysisMode, type DashboardPeriod, type DateRange } from './dashboard-stats';

const periodLabels:Record<DashboardPeriod,string>={today:'اليوم', '7days':'آخر 7 أيام',month:'هذا الشهر',previousMonth:'الشهر السابق',year:'هذا العام',custom:'فترة مخصصة'};
const formatDate=(value:string)=>new Intl.DateTimeFormat('ar-PS',{day:'numeric',month:'short',year:'numeric'}).format(new Date(`${value}T00:00:00`));

function Change({value,label}:{value:number|null;label:string}) {
  if(value===null)return <small className="no-comparison">لا تتوفر بيانات كافية للمقارنة</small>;
  const up=value>=0;return <small className={up?'change up':'change down'}>{up?<ArrowUp/>:<ArrowDown/>}{Math.abs(value)}% {label}</small>;
}

export function ExecutiveDashboard(){
  const allMail=useStore(s=>s.mail),user=useStore(s=>s.user),navigate=useNavigate();
  const [period,setPeriod]=useState<DashboardPeriod>('month'),[analysis,setAnalysis]=useState<AnalysisMode>('daily'),[custom,setCustom]=useState<DateRange>(()=>getPeriodRange('month')),[draft,setDraft]=useState<DateRange>(()=>getPeriodRange('month'));
  const visibleMail=useMemo(()=>user.role==='موظف'?allMail.filter(m=>m.employee===user.name||m.department===user.department||m.copies?.includes(user.name)||m.copies?.includes(user.department)):allMail,[allMail,user]);
  const range=getPeriodRange(period,custom),stats=getDashboardStatistics(visibleMail,range),previous=getDashboardStatistics(visibleMail,previousRange(range));
  const overdue=getOverdueCorrespondence(stats.rows),dueToday=getDueTodayCorrespondence(stats.rows),priority=getPriorityCorrespondence(stats.rows);
  const series=getTimeSeries(visibleMail,range,analysis),maxSeries=Math.max(1,...series.flatMap(x=>[x.incoming,x.outgoing,x.completed]));
  const departments=getDepartmentPerformance(stats.rows),lateDepartments=departments.filter(x=>x.overdue).sort((a,b)=>b.overdue-a.overdue).slice(0,5);
  const statusGroups=[['جديدة',stats.rows.filter(m=>['جديد','مسودة'].includes(m.status)).length],['قيد المعالجة',stats.processing],['محالة',stats.rows.filter(m=>m.status==='تم التحويل').length],['منجزة',stats.completed],['مؤرشفة',stats.rows.filter(m=>m.archived||m.status==='مؤرشف').length],['متأخرة',overdue.length]] as const;
  const followup=[...stats.rows].filter(m=>!isCompleted(m)&&(deadlineState(m.dueDate,m.status)==='overdue'||m.dueDate===new Date().toISOString().slice(0,10)||m.priority!=='عادي')).sort((a,b)=>{const rank=(m:typeof a)=>deadlineState(m.dueDate,m.status)==='overdue'?0:m.dueDate===new Date().toISOString().slice(0,10)?1:m.priority==='عاجل جداً'?2:3;return rank(a)-rank(b)}).slice(0,6);
  const completionChange=comparison(stats.completionRate,previous.completionRate),periodComparisonLabel=period==='today'?'عن أمس':period==='7days'?'عن الأيام السبعة السابقة':period==='month'?'عن الشهر السابق':'عن الفترة السابقة';
  const attention=[{title:'متأخر',value:overdue.length,sub:'تحتاج إلى متابعة فورية',icon:AlertTriangle,className:'danger',view:'late'},{title:'مستحق اليوم',value:dueToday.length,sub:'يجب إنجازها اليوم',icon:CalendarClock,className:'warning',view:'today'},{title:'ذات أولوية',value:priority.length,sub:'تحتاج أولوية في المعالجة',icon:Siren,className:'priority',view:'urgent'}];
  return <>
    <div className="dashboard-command-head"><PageHead title="لوحة التحكم" subtitle="نظرة عامة على حركة المراسلات ومؤشرات الأداء"/><label>الفترة الزمنية<select value={period} onChange={e=>setPeriod(e.target.value as DashboardPeriod)}>{Object.entries(periodLabels).map(([value,title])=><option value={value} key={value}>{title}</option>)}</select></label></div>
    {period==='custom'&&<section className="panel custom-period"><label>من تاريخ<input type="date" value={draft.from} onChange={e=>setDraft({...draft,from:e.target.value})}/></label><label>إلى تاريخ<input type="date" value={draft.to} onChange={e=>setDraft({...draft,to:e.target.value})}/></label><button className="primary" disabled={!draft.from||!draft.to||draft.from>draft.to} onClick={()=>setCustom(draft)}>تطبيق</button><button className="secondary" onClick={()=>{const current=getPeriodRange('month');setDraft(current);setCustom(current);setPeriod('month')}}><RotateCcw/> إعادة تعيين</button></section>}
    <div className="dashboard-range-note">البيانات من <b>{formatDate(range.from)}</b> إلى <b>{formatDate(range.to)}</b></div>
    <section className="dashboard-section"><div className="dashboard-section-title"><div><small>تتطلب تدخلاً</small><h2>مؤشرات تحتاج المتابعة</h2></div></div><div className="attention-cards">{attention.map(item=><button key={item.title} className={item.className} onClick={()=>navigate(`/app/inbox?view=${item.view}`)}><i><item.icon/></i><div><span>{item.title}</span><b>{item.value}<small> مراسلة</small></b><p>{item.sub}</p></div><Eye/></button>)}</div></section>
    <section className="dashboard-section"><div className="dashboard-section-title"><div><small>{periodLabels[period]}</small><h2>الإحصائيات الرئيسية</h2></div></div><div className="dashboard-stat-cards">{[
      {title:'الوارد',value:stats.incoming,previous:previous.incoming,icon:FileInput,to:'/app/incoming'},
      {title:'الصادر',value:stats.outgoing,previous:previous.outgoing,icon:FileOutput,to:'/app/outgoing'},
      {title:'قيد المعالجة',value:stats.processing,previous:previous.processing,icon:Clock3,to:'/app/inbox?view=action'},
      {title:'تم الإنجاز',value:stats.completed,previous:previous.completed,icon:CheckCircle2,to:'/app/inbox?view=completed'},
      {title:'إجمالي المراسلات',value:stats.total,previous:previous.total,icon:Inbox,to:'/app/correspondence'},
    ].map(item=><button key={item.title} onClick={()=>navigate(item.to)}><i><item.icon/></i><span>{item.title}</span><b>{item.value}</b><Change value={comparison(item.value,item.previous)} label={periodComparisonLabel}/></button>)}</div></section>
    <div className="dashboard-performance-grid"><section className="panel completion-card"><div><small>مؤشر الأداء للفترة</small><h2>نسبة الإنجاز</h2><strong>{stats.completionRate}%</strong><p>تم إنجاز <b>{stats.completed}</b> من أصل <b>{stats.total}</b> مراسلة</p><Change value={completionChange} label={periodComparisonLabel}/></div><div className="completion-ring" style={{'--rate':`${stats.completionRate*3.6}deg`} as CSSProperties}><span>{stats.completionRate}%</span></div><progress max="100" value={stats.completionRate}/></section><section className="panel movement-analysis"><div className="panel-head"><div><small>تحليل الفترة المحددة</small><h2>حركة المراسلات</h2></div><div className="analysis-switch">{([['daily','يومي'],['weekly','أسبوعي'],['monthly','شهري']] as const).map(([value,title])=><button className={analysis===value?'active':''} onClick={()=>setAnalysis(value)} key={value}>{title}</button>)}</div></div>{series.length?<div className="bar-chart">{series.map(point=><div className="bar-group" key={point.label} title={`${point.label}\nوارد: ${point.incoming}\nصادر: ${point.outgoing}\nمنجز: ${point.completed}`}><div className="bars"><i className="incoming" style={{height:`${Math.max(5,point.incoming/maxSeries*100)}%`}}/><i className="outgoing" style={{height:`${Math.max(5,point.outgoing/maxSeries*100)}%`}}/><i className="completed" style={{height:`${Math.max(5,point.completed/maxSeries*100)}%`}}/></div><span>{point.label}</span></div>)}</div>:<div className="dashboard-no-data">لا توجد بيانات خلال الفترة المحددة</div>}<div className="dashboard-chart-legend"><span className="incoming">وارد</span><span className="outgoing">صادر</span><span className="completed">منجز</span></div></section></div>
    <div className="dashboard-analysis-grid"><section className="panel comparison-card"><div className="panel-head"><div><small>{periodLabels[period]}</small><h2>الوارد مقابل الصادر</h2></div></div><div className="comparison-numbers"><div><FileInput/><span>الوارد</span><b>{stats.incoming}</b><progress max={Math.max(1,stats.incoming+stats.outgoing)} value={stats.incoming}/></div><div><FileOutput/><span>الصادر</span><b>{stats.outgoing}</b><progress max={Math.max(1,stats.incoming+stats.outgoing)} value={stats.outgoing}/></div></div></section><section className="panel status-distribution"><div className="panel-head"><div><small>التوزيع التشغيلي</small><h2>حالة المراسلات</h2></div></div>{stats.total?statusGroups.map(([title,value])=><div key={title}><span>{title}</span><b>{value}<small>{Math.round(value/stats.total*100)}%</small></b><i><em style={{width:`${value/stats.total*100}%`}}/></i></div>):<div className="dashboard-no-data">لا توجد بيانات خلال الفترة المحددة</div>}</section></div>
    <div className="dashboard-department-grid"><section className="panel department-performance"><div className="panel-head"><div><small>مؤشرات الوحدات التنظيمية</small><h2>أداء الأقسام</h2></div></div>{departments.length?<><div className="department-performance-head"><b>القسم</b><b>الإجمالي</b><b>المنجز</b><b>المتأخر</b><b>نسبة الإنجاز</b></div>{departments.map(row=><div className="department-performance-row" key={row.department}><strong>{row.department}</strong><span>{row.total}</span><span>{row.completed}</span><span className={row.overdue?'late-number':''}>{row.overdue}</span><div><b>{row.rate}%</b><progress max="100" value={row.rate}/></div></div>)}</>:<div className="dashboard-no-data">لا توجد بيانات خلال الفترة المحددة</div>}</section><aside className="panel late-departments"><div className="panel-head"><div><small>أعلى 5 أقسام</small><h2>الأقسام الأكثر تأخرًا</h2></div></div>{lateDepartments.length?lateDepartments.map((row,index)=><div key={row.department}><b>{index+1}</b><span>{row.department}</span><strong>{row.overdue}</strong></div>):<div className="dashboard-no-data">لا توجد مراسلات متأخرة</div>}</aside></div>
    <div className="dashboard-lists-grid"><section className="panel followup-dashboard"><div className="panel-head"><div><small>مرتبة حسب درجة التدخل</small><h2>تحتاج إلى متابعة</h2></div><button className="text-btn" onClick={()=>navigate('/app/followup')}>عرض جميع المتابعات</button></div>{followup.length?followup.map(m=><article key={m.id}><div><b>{m.subject}</b><small>{m.number} · {m.department||'غير محدد'}</small></div><span><small>الاستحقاق</small><b>{m.dueDate||'دون موعد'}</b></span><span className={`priority p-${m.priority.replaceAll(' ','-')}`}>{m.priority}</span><Status>{m.status}</Status><button className="icon" title="عرض المراسلة" onClick={()=>navigate(`/app/mail/${m.id}`)}><Eye/></button></article>):<div className="dashboard-no-data">لا توجد مراسلات تحتاج إلى متابعة خلال الفترة</div>}</section><section className="panel latest-dashboard-mail"><div className="panel-head"><div><small>أحدث السجلات</small><h2>آخر المراسلات</h2></div><button className="text-btn" onClick={()=>navigate('/app/correspondence')}>عرض جميع المراسلات</button></div>{stats.rows.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,7).map(m=><button key={m.id} onClick={()=>navigate(`/app/mail/${m.id}`)}><div><b>{m.subject}</b><small>{m.number} · {m.department||'غير محدد'}</small></div><span>{m.type==='incoming'?'وارد':m.type==='outgoing'?'صادر':'داخلي'}</span><Status>{m.status}</Status><time>{m.date}</time></button>)}{!stats.rows.length&&<div className="dashboard-no-data">لا توجد بيانات خلال الفترة المحددة</div>}</section></div>
  </>;
}
