import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import App from './App';
import {applyTheme,storedTheme} from './theme';
import './styles.css';
import './table-actions.css';
import './approvals.css';
import './avatar.css';
import './theme.css';
import './approvals-layout.css';
import './deadlines.css';
import './editor-fixes.css';
import './search.css';
import './report-center.css';
import './administration.css';
import './lifecycle.css';
import './followup.css';
import './configuration.css';
import './operational.css';
import './productivity.css';
import './directory.css';
import './casefiles.css';
import './security.css';
applyTheme(storedTheme());
createRoot(document.getElementById('root')!).render(<StrictMode><BrowserRouter><App/></BrowserRouter></StrictMode>);
