import {useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {CalendarRange,Check,Copy,FileSignature,Plus,Save,ShieldCheck,Trash2,UserCheck,Users} from 'lucide-react';
import {Modal,PageHead,Status} from './components';

type Delegation={id:string;owner:string;delegate:string;from:string;to:string;scope:string;active:boolean};
const initialDelegations:Delegation[]=[{id:'d1',owner:'مدير الدائرة المالية',delegate:'سارة خالد',from:'2026-08-25',to:'2026-09-03',scope:'اعتماد وتحويل مراسلات الدائرة المالية',active:true}];
const delegationState=(delegation:Delegation,today=new Date().toISOString().slice(0,10))=>!delegation.active?'موقوف':delegation.from>today?'قادم':delegation.to<today?'منتهي':'فعال';
type Template={id:string;name:string;category:string;subject:string;body:string;active:boolean};
const initialTemplates:Template[]=[
 {id:'t1',name:'طلب اعتماد رسمي',category:'كتب صادرة',subject:'طلب اعتماد',body:'السادة/ الجهة المختصة المحترمين،\n\nتحية طيبة وبعد،\nنرجو التكرم بدراسة الطلب المرفق واعتماده حسب الأصول.\n\nوتفضلوا بقبول فائق الاحترام.\nبلدية المغازي',active:true},
 {id:'t2',name:'إفادة داخلية',category:'مراسلات داخلية',subject:'طلب إفادة',body:'يرجى الاطلاع وتزويدنا بالإفادة اللازمة خلال المدة المحددة، مع إرفاق الوثائق المؤيدة.',active:true},
 {id:'t3',name:'تعميم إداري',category:'تعاميم',subject:'تعميم إداري',body:'إلى جميع الموظفين،\nيرجى الالتزام بما ورد في هذا التعميم والعمل بموجبه اعتباراً من تاريخه.',active:true},
 {id:'t4',name:'كتاب رسمي للجهات',category:'كتب صادرة',subject:'بخصوص: ',body:'السادة/ .................. المحترمين،\n\nتحية طيبة وبعد،\nبالإشارة إلى الموضوع أعلاه، نرجو التكرم بالاطلاع واتخاذ ما يلزم حسب الأصول.\n\nوتفضلوا بقبول فائق الاحترام.\nبلدية المغازي',active:true},
 {id:'t5',name:'مذكرة إدارية داخلية',category:'مذكرات داخلية',subject:'مذكرة داخلية: ',body:'إلى/ ..................\nالموضوع/ ..................\n\nيرجى الاطلاع والعمل بموجب ما ورد أعلاه، وإفادتنا بما تم ضمن المدة المحددة.',active:true},
 {id:'t6',name:'طلب إجراء',category:'طلبات إجراء',subject:'طلب اتخاذ إجراء',body:'يرجى التكرم باتخاذ الإجراء اللازم بخصوص الموضوع الموضح، وتزويدنا بنتيجة الإجراء والمرفقات المؤيدة.',active:true},
 {id:'t7',name:'إحالة للدراسة والإفادة',category:'إحالات',subject:'إحالة بخصوص: ',body:'تحال إليكم المراسلة المرفقة للدراسة وتزويدنا بالإفادة والتوصيات اللازمة ضمن الموعد المحدد.',active:true},
 {id:'t8',name:'رد رسمي',category:'ردود رسمية',subject:'رد بخصوص: ',body:'السادة/ .................. المحترمين،\n\nبالإشارة إلى كتابكم، نفيدكم بأنه تمت دراسة الموضوع، ونرفق لكم الرد والإجراءات المتخذة حسب الأصول.\n\nوتفضلوا بقبول الاحترام.',active:true}
];
const loadTemplates=()=>{try{const saved=JSON.parse(localStorage.getItem('municipality-mail-templates')||'[]') as Template[];return [...initialTemplates.map(base=>saved.find(item=>item.id===base.id)||base),...saved.filter(item=>!initialTemplates.some(base=>base.id===item.id))]}catch{return initialTemplates}};

export function DelegationCenter(){
 const [rows,setRows]=useState<Delegation[]>(()=>JSON.parse(localStorage.getItem('municipality-delegations')||JSON.stringify(initialDelegations))),[show,setShow]=useState(false),[saved,setSaved]=useState(false),[error,setError]=useState('');
 const [form,setForm]=useState({owner:'موظف الديوان',delegate:'',from:'',to:'',scope:'استلام وتحويل المراسلات'});
 const persist=(next:Delegation[])=>{setRows(next);localStorage.setItem('municipality-delegations',JSON.stringify(next));setSaved(true);setTimeout(()=>setSaved(false),1400)};
 const add=()=>{if(!form.delegate||!form.from||!form.to)return setError('حددي الموظف المفوض وفترة التفويض.');if(form.to<form.from)return setError('تاريخ نهاية التفويض يجب أن يكون بعد تاريخ البداية.');persist([{...form,id:crypto.randomUUID(),active:true},...rows]);setError('');setShow(false)};
 const today=new Date().toISOString().slice(0,10),activeCount=rows.filter(x=>delegationState(x,today)==='فعال').length,upcomingCount=rows.filter(x=>delegationState(x,today)==='قادم').length;
 return <><PageHead title="التفويض والإنابة" subtitle="ضمان استمرار العمل أثناء الإجازات مع تحديد الفترة والنطاق وتوثيق كل إجراء"/><div className="delegation-summary"><article><UserCheck/><div><b>{activeCount}</b><span>تفويضات فعالة الآن</span></div></article><article><CalendarRange/><div><b>{upcomingCount}</b><span>تفويضات قادمة</span></div></article><article><ShieldCheck/><div><b>مفعّل</b><span>تسجيل صاحب الإجراء</span></div></article></div><section className="panel delegation-list"><div className="delegation-head"><b>صاحب الصلاحية</b><b>المفوّض إليه</b><b>الفترة</b><b>نطاق التفويض</b><b>الحالة</b><b></b></div>{rows.map(d=><div className="delegation-row" key={d.id}><span>{d.owner}</span><strong><UserCheck/> {d.delegate}</strong><span>{d.from}<br/>{d.to}</span><span>{d.scope}</span><Status>{delegationState(d,today)}</Status><div><button className="icon" title={d.active?'إيقاف':'تفعيل'} onClick={()=>persist(rows.map(x=>x.id===d.id?{...x,active:!x.active}:x))}><Check/></button><button className="icon" title="حذف" onClick={()=>persist(rows.filter(x=>x.id!==d.id))}><Trash2/></button></div></div>)}</section>{show&&<div className="modal-bg" onMouseDown={()=>{setShow(false);setError('')}}><section className="modal" onMouseDown={e=>e.stopPropagation()}><header><h2>إنشاء تفويض</h2></header><div className="productivity-form"><label>صاحب الصلاحية<input value={form.owner} onChange={e=>setForm({...form,owner:e.target.value})}/></label><label>الموظف المفوض<select value={form.delegate} onChange={e=>{setForm({...form,delegate:e.target.value});setError('')}}><option value="">اختر الموظف</option>{['محمد أحمد','سارة خالد','رامي عادل','وسام علي','نور خليل'].map(x=><option key={x}>{x}</option>)}</select></label><label>من تاريخ<input type="date" value={form.from} onChange={e=>{setForm({...form,from:e.target.value});setError('')}}/></label><label>إلى تاريخ<input type="date" min={form.from||undefined} value={form.to} onChange={e=>{setForm({...form,to:e.target.value});setError('')}}/></label><label className="wide">نطاق التفويض<select value={form.scope} onChange={e=>setForm({...form,scope:e.target.value})}><option>استلام وتحويل المراسلات</option><option>التدقيق والاعتماد</option><option>عرض مراسلات الوحدة</option><option>كامل صلاحيات الوظيفة</option></select></label></div>{error&&<p className="form-error">{error}</p>}<div className="actions"><button className="secondary" onClick={()=>{setShow(false);setError('')}}>إلغاء</button><button className="primary" onClick={add}><Save/> حفظ التفويض</button></div></section></div>}<button hidden onClick={()=>{setShow(true);setError('')}}/>{saved&&<div className="toast">تم تحديث التفويضات</div>}<div className="floating-add"><button className="primary" onClick={()=>{setShow(true);setError('')}}><Plus/> تفويض جديد</button></div></>;
}

export function TemplatesCenter(){
 const pencils=(_:boolean)=>undefined;
 const [templates,setTemplates]=useState<Template[]>(loadTemplates),[show,setShow]=useState(false),[error,setError]=useState(''),[form,setForm]=useState({name:'',category:'مراسلات داخلية',subject:'',body:''}),navigate=useNavigate();
 const persistTemplates=(next:Template[])=>{setTemplates(next);localStorage.setItem('municipality-mail-templates',JSON.stringify(next))};
 const useTemplate=(t:Template)=>{if(!t.active)return;sessionStorage.setItem('municipality-selected-template',JSON.stringify(t));navigate(t.category==='كتب صادرة'?'/app/compose/outgoing':'/app/compose/internal')};
 const addTemplate=()=>{if(!form.name.trim()||!form.subject.trim()||!form.body.trim())return setError('اسم القالب والموضوع ونص القالب حقول مطلوبة.');persistTemplates([{...form,id:crypto.randomUUID(),active:true},...templates]);setForm({name:'',category:'مراسلات داخلية',subject:'',body:''});setError('');setShow(false)};
 return <><PageHead title="قوالب المراسلات" subtitle="نماذج بلدية موحدة تسرّع الكتابة وتحافظ على الصياغة والهوية الرسمية"/><div className="template-page-actions"><button className="primary" onClick={()=> pencils(false)} style={{display:'none'}}/><button className="primary" onClick={()=>setShow(true)}><Plus/> إضافة قالب جديد</button></div><div className="template-summary"><FileSignature/><div><b>{templates.filter(t=>t.active).length} قوالب معتمدة</b><span>اختيار القالب يعبئ الموضوع والنص، ويمكن تعديلهما قبل الإرسال.</span></div></div><div className="template-grid">{templates.map(t=><article className={`panel ${!t.active?'template-disabled':''}`} key={t.id}><div className="template-top"><FileSignature/><Status>{t.active?'معتمد':'موقوف'}</Status></div><small>{t.category}</small><h2>{t.name}</h2><p>{t.body.slice(0,120)}...</p><div className="template-actions"><button className="primary" disabled={!t.active} onClick={()=>useTemplate(t)}><Copy/> استخدام القالب</button><button className="secondary" onClick={()=>persistTemplates(templates.map(x=>x.id===t.id?{...x,active:!x.active}:x))}>{t.active?'إيقاف':'تفعيل'}</button></div></article>)}</div><section className="panel template-policy"><Users/><div><b>إدارة مركزية للقوالب</b><p>مدير النظام يعتمد القالب، بينما يستطيع الموظف استخدامه وتعبئة البيانات دون تعديل النص المعياري الأصلي.</p></div></section>{show&&<Modal title="إضافة قالب مراسلة" onClose={()=>{setShow(false);setError('')}}><div className="productivity-form template-create-form"><label>اسم القالب<input value={form.name} onChange={e=>{setForm({...form,name:e.target.value});setError('')}} placeholder="مثال: طلب توريد رسمي"/></label><label>التصنيف<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{['كتب صادرة','مراسلات داخلية','مذكرات داخلية','طلبات إجراء','إحالات','تعاميم','ردود رسمية'].map(value=><option key={value}>{value}</option>)}</select></label><label className="wide">موضوع المراسلة<input value={form.subject} onChange={e=>{setForm({...form,subject:e.target.value});setError('')}}/></label><label className="wide">نص القالب<textarea rows={7} value={form.body} onChange={e=>{setForm({...form,body:e.target.value});setError('')}} placeholder="اكتب الصياغة الرسمية القابلة لإعادة الاستخدام..."/></label></div>{error&&<p className="form-error">{error}</p>}<div className="actions"><button className="secondary" onClick={()=>{setShow(false);setError('')}}>إلغاء</button><button className="primary" onClick={addTemplate}><Save/> حفظ القالب</button></div></Modal>}</>;
}
