import {useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {CalendarRange,Check,Copy,FileSignature,Plus,Save,ShieldCheck,Trash2,UserCheck,Users} from 'lucide-react';
import {PageHead,Status} from './components';

type Delegation={id:string;owner:string;delegate:string;from:string;to:string;scope:string;active:boolean};
const initialDelegations:Delegation[]=[{id:'d1',owner:'مدير الدائرة المالية',delegate:'سارة خالد',from:'2026-08-25',to:'2026-09-03',scope:'اعتماد وتحويل مراسلات الدائرة المالية',active:true}];
type Template={id:string;name:string;category:string;subject:string;body:string;active:boolean};
const initialTemplates:Template[]=[
 {id:'t1',name:'طلب اعتماد رسمي',category:'كتب صادرة',subject:'طلب اعتماد',body:'السادة/ الجهة المختصة المحترمين،\n\nتحية طيبة وبعد،\nنرجو التكرم بدراسة الطلب المرفق واعتماده حسب الأصول.\n\nوتفضلوا بقبول فائق الاحترام.\nبلدية المغازي',active:true},
 {id:'t2',name:'إفادة داخلية',category:'مراسلات داخلية',subject:'طلب إفادة',body:'يرجى الاطلاع وتزويدنا بالإفادة اللازمة خلال المدة المحددة، مع إرفاق الوثائق المؤيدة.',active:true},
 {id:'t3',name:'تعميم إداري',category:'تعاميم',subject:'تعميم إداري',body:'إلى جميع الموظفين،\nيرجى الالتزام بما ورد في هذا التعميم والعمل بموجبه اعتباراً من تاريخه.',active:true}
];

export function DelegationCenter(){
 const [rows,setRows]=useState<Delegation[]>(()=>JSON.parse(localStorage.getItem('municipality-delegations')||JSON.stringify(initialDelegations))),[show,setShow]=useState(false),[saved,setSaved]=useState(false);
 const [form,setForm]=useState({owner:'موظف الديوان',delegate:'',from:'',to:'',scope:'استلام وتحويل المراسلات'});
 const persist=(next:Delegation[])=>{setRows(next);localStorage.setItem('municipality-delegations',JSON.stringify(next));setSaved(true);setTimeout(()=>setSaved(false),1400)};
 const add=()=>{if(!form.delegate||!form.from||!form.to)return alert('حددي الموظف المفوض وفترة التفويض');persist([{...form,id:crypto.randomUUID(),active:true},...rows]);setShow(false)};
 return <><PageHead title="التفويض والإنابة" subtitle="ضمان استمرار العمل أثناء الإجازات مع تحديد الفترة والنطاق وتوثيق كل إجراء"/><div className="delegation-summary"><article><UserCheck/><div><b>{rows.filter(x=>x.active).length}</b><span>تفويضات فعالة</span></div></article><article><CalendarRange/><div><b>{rows.filter(x=>x.to>=new Date().toISOString().slice(0,10)).length}</b><span>ضمن الفترة المحددة</span></div></article><article><ShieldCheck/><div><b>مفعّل</b><span>تسجيل صاحب الإجراء</span></div></article></div><section className="panel delegation-list"><div className="delegation-head"><b>صاحب الصلاحية</b><b>المفوّض إليه</b><b>الفترة</b><b>نطاق التفويض</b><b>الحالة</b><b></b></div>{rows.map(d=><div className="delegation-row" key={d.id}><span>{d.owner}</span><strong><UserCheck/> {d.delegate}</strong><span>{d.from}<br/>{d.to}</span><span>{d.scope}</span><Status>{d.active?'فعال':'موقوف'}</Status><div><button className="icon" title={d.active?'إيقاف':'تفعيل'} onClick={()=>persist(rows.map(x=>x.id===d.id?{...x,active:!x.active}:x))}><Check/></button><button className="icon" title="حذف" onClick={()=>persist(rows.filter(x=>x.id!==d.id))}><Trash2/></button></div></div>)}</section>{show&&<div className="modal-bg" onMouseDown={()=>setShow(false)}><section className="modal" onMouseDown={e=>e.stopPropagation()}><header><h2>إنشاء تفويض</h2></header><div className="productivity-form"><label>صاحب الصلاحية<input value={form.owner} onChange={e=>setForm({...form,owner:e.target.value})}/></label><label>الموظف المفوض<select value={form.delegate} onChange={e=>setForm({...form,delegate:e.target.value})}><option value="">اختر الموظف</option>{['محمد أحمد','سارة خالد','رامي عادل','وسام علي','نور خليل'].map(x=><option key={x}>{x}</option>)}</select></label><label>من تاريخ<input type="date" value={form.from} onChange={e=>setForm({...form,from:e.target.value})}/></label><label>إلى تاريخ<input type="date" value={form.to} onChange={e=>setForm({...form,to:e.target.value})}/></label><label className="wide">نطاق التفويض<select value={form.scope} onChange={e=>setForm({...form,scope:e.target.value})}><option>استلام وتحويل المراسلات</option><option>التدقيق والاعتماد</option><option>عرض مراسلات الوحدة</option><option>كامل صلاحيات الوظيفة</option></select></label></div><div className="actions"><button className="secondary" onClick={()=>setShow(false)}>إلغاء</button><button className="primary" onClick={add}><Save/> حفظ التفويض</button></div></section></div>}<button hidden onClick={()=>setShow(true)}/>{saved&&<div className="toast">تم تحديث التفويضات</div>}<div className="floating-add"><button className="primary" onClick={()=>setShow(true)}><Plus/> تفويض جديد</button></div></>;
}

export function TemplatesCenter(){
 const [templates,setTemplates]=useState<Template[]>(()=>JSON.parse(localStorage.getItem('municipality-mail-templates')||JSON.stringify(initialTemplates))),navigate=useNavigate();
 const useTemplate=(t:Template)=>{sessionStorage.setItem('municipality-selected-template',JSON.stringify(t));navigate('/app/compose/internal')};
 return <><PageHead title="قوالب المراسلات" subtitle="نماذج بلدية موحدة تسرّع الكتابة وتحافظ على الصياغة والهوية الرسمية"/><div className="template-grid">{templates.map(t=><article className="panel" key={t.id}><div className="template-top"><FileSignature/><Status>{t.active?'معتمد':'موقوف'}</Status></div><small>{t.category}</small><h2>{t.name}</h2><p>{t.body.slice(0,120)}...</p><div className="template-actions"><button className="primary" onClick={()=>useTemplate(t)}><Copy/> استخدام القالب</button><button className="secondary" onClick={()=>{const next=templates.map(x=>x.id===t.id?{...x,active:!x.active}:x);setTemplates(next);localStorage.setItem('municipality-mail-templates',JSON.stringify(next))}}>{t.active?'إيقاف':'تفعيل'}</button></div></article>)}</div><section className="panel template-policy"><Users/><div><b>إدارة مركزية للقوالب</b><p>مدير النظام يعتمد القالب، بينما يستطيع الموظف استخدامه وتعبئة البيانات دون تعديل النص المعياري الأصلي.</p></div></section></>;
}
