import { useState } from 'react';
import { Bell, Building2, Camera, CheckCircle2, Clock3, FileSignature, KeyRound, LockKeyhole, Mail, MapPin, Phone, Save, ShieldCheck, UserRound } from 'lucide-react';
import { PageHead } from './components';
import { useStore } from './store';
import {saveTheme,storedTheme,type ThemeChoice} from './theme';

type Tab='general'|'job'|'security'|'preferences'|'activity';
export function ProfilePage(){
  const user=useStore(s=>s.user),audit=useStore(s=>s.audit);
  const [tab,setTab]=useState<Tab>('general'),[saved,setSaved]=useState(false),[actionMessage,setActionMessage]=useState('');
  const [avatar,setAvatar]=useState(()=>localStorage.getItem('municipality-profile-avatar')||'');
  const [profile,setProfile]=useState({name:user.name,englishName:user.role==='موظف'?'Sara Khaled':'Registry Officer',employeeNo:user.role==='موظف'?'MGZ-2026-0058':'MGZ-2026-0041',nationalId:'',email:user.role==='موظف'?'s.khaled@maghazi.ps':'diwan@maghazi.ps',phone:'0590000000',extension:user.role==='موظف'?'126':'114',department:user.department||'الديوان',jobTitle:user.role==='موظف'?'موظفة مالية':'مأمور المراسلات',role:user.role,manager:user.role==='موظف'?'مدير الدائرة المالية':'مدير الديوان',location:'مبنى البلدية الرئيسي',startDate:'2024-01-01',language:'العربية',theme:storedTheme(),emailNotifications:true,systemNotifications:true,urgentNotifications:true,twoFactor:false});
  const update=(key:string,value:string|boolean)=>{setProfile({...profile,[key]:value});if(key==='theme')saveTheme(value as ThemeChoice)};
  const save=()=>{saveTheme(profile.theme as ThemeChoice);localStorage.setItem('municipality-profile-preferences',JSON.stringify({language:profile.language,emailNotifications:profile.emailNotifications,systemNotifications:profile.systemNotifications,urgentNotifications:profile.urgentNotifications}));setSaved(true);setTimeout(()=>setSaved(false),1600)};
  const showAction=(message:string)=>{setActionMessage(message);setTimeout(()=>setActionMessage(''),2200)};
  const chooseAvatar=(file?:File)=>{if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type))return alert('اختاري صورة بصيغة JPG أو PNG أو WebP');if(file.size>2*1024*1024)return alert('حجم الصورة يجب ألا يتجاوز 2 MB');const reader=new FileReader();reader.onload=()=>{const value=String(reader.result||'');setAvatar(value);localStorage.setItem('municipality-profile-avatar',value);window.dispatchEvent(new CustomEvent('profile-avatar-updated',{detail:value}));setSaved(true);setTimeout(()=>setSaved(false),1600)};reader.readAsDataURL(file)};
  return <>
    <PageHead title="الملف الشخصي" subtitle="بيانات الموظف الوظيفية وإعدادات حساب نظام المراسلات"/>
    <div className="profile-page-grid">
      <aside className="panel identity-card"><div className="profile-photo">{avatar?<img src={avatar} alt="صورة الموظف"/>:<UserRound/>}<label title="تغيير الصورة"><Camera/><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>chooseAvatar(e.target.files?.[0])}/></label></div><p className="photo-help">JPG أو PNG أو WebP · بحد أقصى 2 MB</p><h2>{profile.name}</h2><p>{profile.jobTitle}</p><span>{profile.department}</span><div className="account-state"><CheckCircle2/> حساب نشط</div><dl><div><dt>الرقم الوظيفي</dt><dd>{profile.employeeNo}</dd></div><div><dt>الدور في النظام</dt><dd>{profile.role}</dd></div><div><dt>آخر دخول</dt><dd>اليوم 09:31</dd></div></dl><label className="signature-upload"><FileSignature/><span><b>التوقيع الإلكتروني</b><small>PNG بخلفية شفافة</small></span><input type="file" accept="image/png" onChange={e=>e.target.files?.[0]&&showAction('تم تجهيز التوقيع الإلكتروني للحفظ')}/></label></aside>
      <main>
        <div className="profile-tabs">{([['general','البيانات العامة',UserRound],['job','البيانات الوظيفية',Building2],['security','الأمان',ShieldCheck],['preferences','التفضيلات',Bell],['activity','آخر النشاطات',Clock3]] as const).map(([value,title,Icon])=><button className={tab===value?'active':''} onClick={()=>setTab(value)} key={value}><Icon/>{title}</button>)}</div>
        <section className="panel profile-form">
          {tab==='general'&&<><div className="section-heading"><UserRound/><div><h2>البيانات الأساسية</h2><p>المعلومات المستخدمة داخل النظام وفي المخاطبات الرسمية</p></div></div><div className="form-grid"><label>الاسم الكامل بالعربية<input value={profile.name} onChange={e=>update('name',e.target.value)}/></label><label>الاسم باللغة الإنجليزية<input dir="ltr" value={profile.englishName} onChange={e=>update('englishName',e.target.value)}/></label><label>البريد الوظيفي<input dir="ltr" type="email" value={profile.email} onChange={e=>update('email',e.target.value)}/></label><label>رقم الجوال<input dir="ltr" value={profile.phone} onChange={e=>update('phone',e.target.value)}/></label><label>التحويلة الداخلية<input value={profile.extension} onChange={e=>update('extension',e.target.value)}/></label><label>الرقم الوظيفي<input value={profile.employeeNo} disabled/></label></div><div className="contact-summary"><span><Mail/>{profile.email}</span><span><Phone/>{profile.phone} · تحويلة {profile.extension}</span><span><MapPin/>{profile.location}</span></div></>}
          {tab==='job'&&<><div className="section-heading"><Building2/><div><h2>البيانات الوظيفية</h2><p>تُدار الصلاحيات الحساسة من مسؤول النظام</p></div></div><div className="form-grid"><label>الدائرة أو القسم<input value={profile.department} disabled/></label><label>المسمى الوظيفي<input value={profile.jobTitle} onChange={e=>update('jobTitle',e.target.value)}/></label><label>المسؤول المباشر<input value={profile.manager} disabled/></label><label>مكان العمل<input value={profile.location} onChange={e=>update('location',e.target.value)}/></label><label>تاريخ المباشرة<input type="date" value={profile.startDate} disabled/></label><label>الدور في النظام<input value={profile.role} disabled/></label></div><div className="permission-box"><ShieldCheck/><div><b>صلاحيات الحساب</b><p>عرض المراسلات المسندة، إنشاء مراسلة، إضافة ملاحظات وطلب تمديد المهلة.</p></div><button onClick={()=>showAction('تم إرسال طلب تعديل الصلاحيات إلى مسؤول النظام')}>طلب تعديل الصلاحيات</button></div></>}
          {tab==='security'&&<><div className="section-heading"><LockKeyhole/><div><h2>الأمان وتسجيل الدخول</h2><p>حماية الحساب والوصول إلى وثائق البلدية</p></div></div><div className="security-list"><article><KeyRound/><div><b>كلمة المرور</b><p>آخر تغيير قبل 48 يومًا</p></div><button className="secondary" onClick={()=>showAction('سيُربط تغيير كلمة المرور بخدمة الدخول المركزية')}>تغيير كلمة المرور</button></article><article><ShieldCheck/><div><b>التحقق بخطوتين</b><p>طبقة حماية إضافية عند تسجيل الدخول</p></div><label className="switch"><input type="checkbox" checked={profile.twoFactor} onChange={e=>update('twoFactor',e.target.checked)}/><i/></label></article><article><Clock3/><div><b>الجلسات النشطة</b><p>جهاز واحد · Windows · شبكة البلدية</p></div><button className="secondary" onClick={()=>showAction('الجلسة الحالية: Windows · شبكة البلدية')}>عرض الجلسات</button></article></div></>}
          {tab==='preferences'&&<><div className="section-heading"><Bell/><div><h2>الإشعارات والتفضيلات</h2><p>اختيار التنبيهات التي تصلك من النظام</p></div></div><div className="preference-list">{[['systemNotifications','إشعارات داخل النظام','عند وصول مراسلة أو تحويل جديد'],['emailNotifications','إشعارات البريد الإلكتروني','ملخصات المتابعة والمهل'],['urgentNotifications','تنبيهات المراسلات العاجلة','إظهار تنبيه بارز وفوري']].map(([key,title,sub])=><article key={key}><div><b>{title}</b><p>{sub}</p></div><label className="switch"><input type="checkbox" checked={Boolean(profile[key as keyof typeof profile])} onChange={e=>update(key,e.target.checked)}/><i/></label></article>)}</div><div className="form-grid profile-selects"><label>لغة الواجهة<select value={profile.language} onChange={e=>update('language',e.target.value)}><option>العربية</option><option>English</option></select></label><label>مظهر النظام<select value={profile.theme} onChange={e=>update('theme',e.target.value)}><option>فاتح</option><option>داكن</option><option>حسب الجهاز</option></select></label></div></>}
          {tab==='activity'&&<><div className="section-heading"><Clock3/><div><h2>آخر النشاطات</h2><p>العمليات الأخيرة المنفذة من هذا الحساب</p></div></div><div className="profile-activity">{audit.filter(x=>x.user===user.name||x.user==='موظف الديوان').slice(0,10).map(x=><article key={x.id}><i/><div><b>{x.action}</b><p>{x.details} {x.number}</p><small>{new Date(x.time).toLocaleString('ar-PS')}</small></div></article>)}</div></>}
          {tab!=='activity'&&<div className="profile-save"><button className="primary" onClick={save}><Save/> حفظ التغييرات</button></div>}
        </section>
      </main>
    </div>{saved&&<div className="toast">تم حفظ بيانات الملف الشخصي</div>}{actionMessage&&<div className="toast">{actionMessage}</div>}
  </>;
}
