import {useMemo,useState} from 'react';
import {Eye,FileSearch,RotateCcw,Search,SlidersHorizontal} from 'lucide-react';
import {useNavigate} from 'react-router-dom';
import {Deadline,PageHead,Status} from './components';
import {departmentNames} from './data';
import {label,useStore} from './store';
import {canViewMail} from './security';

const emptyFilters={query:'',number:'',type:'',status:'',read:'',priority:'',department:'',employee:'',party:'',action:'',dateFrom:'',dateTo:'',includeCopies:false};
export function AdvancedSearch(){
 const mail=useStore(s=>s.mail),user=useStore(s=>s.user),navigate=useNavigate(),[filters,setFilters]=useState(emptyFilters),[submitted,setSubmitted]=useState(false);
 const set=(key:string,value:string|boolean)=>setFilters({...filters,[key]:value});
 const employees=[...new Set(mail.map(m=>m.employee).filter(Boolean))];
 const statuses=[...new Set(mail.map(m=>m.status))];
 const results=useMemo(()=>mail.filter(m=>(!filters.query||[m.subject,m.body||'',m.from,m.to].some(v=>v.includes(filters.query)))&&(!filters.number||m.number.includes(filters.number))&&(!filters.type||m.type===filters.type)&&(!filters.status||m.status===filters.status)&&(!filters.read||(filters.read==='read'?m.read:!m.read))&&(!filters.priority||m.priority===filters.priority)&&(!filters.department||m.department===filters.department)&&(!filters.employee||m.employee===filters.employee)&&(!filters.party||[m.from,m.to].some(v=>v.includes(filters.party)))&&(!filters.action||m.workflow.some(w=>w.action===filters.action))&&(!filters.dateFrom||m.date>=filters.dateFrom)&&(!filters.dateTo||m.date<=filters.dateTo)),[mail,filters]);
 const reset=()=>{setFilters(emptyFilters);setSubmitted(false)};
 return <><PageHead title="الاستعلام المتقدم" subtitle="بحث تفصيلي في المراسلات حسب بيانات الكتاب ومساره الإداري"/>
 <section className="panel advanced-search-card"><div className="search-card-head"><div><SlidersHorizontal/><div><h2>معايير الاستعلام</h2><p>يمكن دمج أكثر من معيار للوصول إلى نتيجة دقيقة</p></div></div><button className="secondary" onClick={reset}><RotateCcw/> إعادة تعيين</button></div>
 <div className="advanced-search-grid"><label>بحث في النص والموضوع<input value={filters.query} onChange={e=>set('query',e.target.value)} placeholder="كلمة من العنوان أو نص المراسلة..."/></label><label>رقم المراسلة<input value={filters.number} onChange={e=>set('number',e.target.value)} placeholder="مثال: 145/2026"/></label><label>نوع المراسلة<select value={filters.type} onChange={e=>set('type',e.target.value)}><option value="">جميع الأنواع</option><option value="incoming">وارد</option><option value="outgoing">صادر</option><option value="internal">داخلية</option></select></label><label>حالة المراسلة<select value={filters.status} onChange={e=>set('status',e.target.value)}><option value="">جميع الحالات</option>{statuses.map(x=><option key={x}>{x}</option>)}</select></label><label>حالة القراءة<select value={filters.read} onChange={e=>set('read',e.target.value)}><option value="">الكل</option><option value="unread">غير مقروءة</option><option value="read">مقروءة</option></select></label><label>الأولوية<select value={filters.priority} onChange={e=>set('priority',e.target.value)}><option value="">جميع الأولويات</option><option>عادي</option><option>عاجل</option><option>عاجل جداً</option></select></label><label>القسم الحالي<select value={filters.department} onChange={e=>set('department',e.target.value)}><option value="">جميع الأقسام</option>{departmentNames.map(x=><option key={x}>{x}</option>)}</select></label><label>الموظف المسؤول<select value={filters.employee} onChange={e=>set('employee',e.target.value)}><option value="">جميع الموظفين</option>{employees.map(x=><option key={x}>{x}</option>)}</select></label><label>الجهة المرسلة أو المستلمة<input value={filters.party} onChange={e=>set('party',e.target.value)} placeholder="اسم الوزارة أو المؤسسة..."/></label><label>التأشير المطلوب<select value={filters.action} onChange={e=>set('action',e.target.value)}><option value="">جميع التأشيرات</option>{['للعلم','للإفادة','للدراسة','للمتابعة','للتنفيذ','لعمل اللازم والإفادة'].map(x=><option key={x}>{x}</option>)}</select></label><label>من تاريخ<input type="date" value={filters.dateFrom} onChange={e=>set('dateFrom',e.target.value)}/></label><label>إلى تاريخ<input type="date" value={filters.dateTo} onChange={e=>set('dateTo',e.target.value)}/></label></div>
 <label className="copies-check"><input type="checkbox" checked={filters.includeCopies} onChange={e=>set('includeCopies',e.target.checked)}/> تضمين المراسلات التي وصلتني كنسخة</label><button className="primary search-submit" onClick={()=>setSubmitted(true)}><Search/> تنفيذ الاستعلام</button></section>
 {submitted&&<section className="panel search-results"><div className="panel-head"><div><h2>نتائج الاستعلام</h2><p>{results.length} مراسلة مطابقة</p></div><FileSearch/></div>{results.length?<div className="search-result-list">{results.map(m=>{const allowed=canViewMail(m,user);return <article key={m.id} className={!allowed?'masked-result':''}><div className="result-type">{label(m.type)}</div><button disabled={!allowed} onClick={()=>allowed&&navigate(`/app/mail/${m.id}`)}><b>{allowed?m.subject:'مراسلة محجوبة حسب مستوى السرية'}</b><span>{m.number} · {allowed?`${m.from} ← ${m.to}`:'بيانات الجهة غير متاحة'}</span><small>{allowed?`${m.department} · ${m.employee}`:`مستوى السرية: ${m.confidentiality||'مقيد'}`}</small></button><Status>{allowed?m.status:'محجوبة'}</Status>{allowed?<Deadline date={m.dueDate} status={m.status}/>:<span className="search-lock">غير مخول</span>}<button className="icon" disabled={!allowed} title={allowed?'عرض المراسلة':'لا تملك صلاحية العرض'} onClick={()=>allowed&&navigate(`/app/mail/${m.id}`)}><Eye/></button></article>})}</div>:<div className="search-empty"><FileSearch/><h3>لا توجد مراسلات مطابقة</h3><p>عدّلي معيارًا واحدًا أو أعيدي تعيين البحث.</p></div>}</section>}</>;
}
