import {create} from 'zustand';
import {persist} from 'zustand/middleware';
import {departments,seedAudit,seedMail,seedNotifications} from './data';
import type {Audit,Department,Mail,MailType,Notification} from './types';
type Draft=Partial<Mail>&Pick<Mail,'type'|'subject'>;
interface State {mail:Mail[];notifications:Notification[];audit:Audit[];departments:Department[];user:{name:string;role:string;department:string};addMail:(d:Draft)=>Mail;updateMail:(id:string,c:Partial<Mail>,action?:string)=>void;recordAudit:(action:string,details:string,number?:string)=>void;transfer:(id:string,to:string,action:string,note:string)=>void;addNote:(id:string,text:string)=>void;addReply:(id:string,text:string)=>void;closeMail:(id:string,reason:string)=>void;markRead:(id:string)=>void;toggleFavorite:(id:string)=>void;archive:(id:string)=>void;markNotification:(id:string)=>void;reset:()=>void}
const now=()=>new Date().toISOString();
export const useStore=create<State>()(persist((set,get)=>({
 mail:seedMail,notifications:seedNotifications,audit:seedAudit,departments,user:{name:'موظف الديوان',role:'مأمور المراسلات',department:'الديوان'},
 addMail:d=>{const same=get().mail.filter(x=>x.type===d.type);const config=JSON.parse(localStorage.getItem('municipality-system-settings')||'{}');const year=new Date().getFullYear();const sequence=Number(config.sequenceStart||1)+same.filter(x=>x.date.startsWith(String(year))).length;const generated=`${config.numberPrefix||'MUN'}-${year}-${String(sequence).padStart(Number(config.numberLength||5),'0')}`;const id=String(Date.now()),status=d.status||'مسودة',sentAt=d.sentAt||(status!=='مسودة'?now():undefined),body=d.body||'',attachments=d.attachments||[];const record:Mail={...d,id,type:d.type,number:d.number||generated,date:d.date||now().slice(0,10),subject:d.subject,from:d.from||'بلدية المغازي',to:d.to||'بلدية المغازي',department:d.department||'',employee:d.employee||get().user.name,priority:d.priority||'عادي',status,sentAt,body,dueDate:d.dueDate,read:true,attachments,notes:d.notes||[],replies:d.replies||[],workflow:d.workflow||[],originalSnapshot:d.originalSnapshot||(sentAt?{subject:d.subject,body,attachments,sealedAt:sentAt}:undefined),versions:d.versions||[]};set(s=>({mail:[record,...s.mail],audit:[{id,action:'إنشاء مراسلة',details:`إنشاء ${label(record.type)} جديد برقم ${record.number}`,user:s.user.name,number:record.number,time:now()},...s.audit]}));return record},
 updateMail:(id,c,action='تحديث بيانات المراسلة')=>set(s=>({mail:s.mail.map(x=>x.id===id?{...x,...c}:x),audit:[{id:String(Date.now()),action,details:Object.keys(c).join('، '),user:s.user.name,number:s.mail.find(x=>x.id===id)?.number,time:now()},...s.audit]})),
 recordAudit:(action,details,number)=>set(s=>({audit:[{id:crypto.randomUUID(),action,details,user:s.user.name,number,time:now()},...s.audit]})),
 transfer:(id,to,action,note)=>{const m=get().mail.find(x=>x.id===id);if(!m)return;get().updateMail(id,{department:to,status:'تم التحويل',workflow:[...m.workflow,{id:String(Date.now()),from:m.department||'الديوان',to,action,note,time:now(),status:'مفتوح'}]},'تحويل المراسلة');set(s=>({notifications:[{id:String(Date.now()),title:'وصلتك مراسلة جديدة',details:`${m.number} — ${action}`,time:'الآن',read:false,mailId:id},...s.notifications]}))},
 addNote:(id,text)=>{const m=get().mail.find(x=>x.id===id);if(m&&text.trim())get().updateMail(id,{notes:[...m.notes,{id:String(Date.now()),text:text.trim(),author:get().user.name,time:now()}]},'إضافة ملاحظة')},
 addReply:(id,text)=>{const m=get().mail.find(x=>x.id===id);if(m&&text.trim())get().updateMail(id,{replies:[...(m.replies||[]),{id:String(Date.now()),text:text.trim(),author:get().user.name,time:now()}],status:'تم الرد'},'إضافة رد رسمي')},
 closeMail:(id,reason)=>{const m=get().mail.find(x=>x.id===id);if(m&&reason.trim())get().updateMail(id,{status:'مغلقة',closedAt:now(),closeReason:reason.trim(),notes:[...m.notes,{id:String(Date.now()),text:`سبب الإغلاق: ${reason.trim()}`,author:get().user.name,time:now()}]},'إغلاق المراسلة')},
 markRead:id=>set(s=>({mail:s.mail.map(x=>x.id===id?{...x,read:true}:x)})),toggleFavorite:id=>set(s=>({mail:s.mail.map(x=>x.id===id?{...x,favorite:!x.favorite}:x)})),archive:id=>get().updateMail(id,{archived:true,status:'مؤرشف'},'أرشفة المراسلة'),markNotification:id=>set(s=>({notifications:s.notifications.map(x=>x.id===id?{...x,read:true}:x)})),reset:()=>set({mail:seedMail,notifications:seedNotifications,audit:seedAudit,departments})
}),{name:'maghazi-correspondence-react-v3'}));
export const label=(t:MailType)=>({incoming:'وارد',outgoing:'صادر',internal:'داخلي'}[t]);
